Address some possible issues in 1.2.11
javascript-tutorial/uk.javascript.info pull request #112
Opened 2020-09-20 11:36 UTC by vsemozhetbyt

[See also PR for the original](https://github.com/javascript-tutorial/en.javascript.info/pull/2134).

2020-10-02 15:46 UTC, UkrainianCitizen requested changes
> @tarasyyyk **КРИТИЧНО**: який переклад для _truthy/falsy_? В глосарії немає. Потрібно якось розділяти _true/false_ та _truthy/falsy_ в перекладі, це не одне і те саме. Я рев'ювив [ПР ](https://github.com/javascript-tutorial/uk.javascript.info/pull/112/files) і усюди бачив, що _truthy/falsy_ перекладається як _true/false_.

2020-10-02 15:46 UTC, UkrainianCitizen commented on 1-js/02-first-steps/11-logical-operators/article.md
> +    Деколи таку конструкцію використовують, щоб виконувати команди лише за умови неправдивості умови ліворуч від оператора.
Хибності. Чи тут *falsy*? Скоріше так, треба встановити переклад для *truthy/falsy* аби їх розрізняти.

2020-10-02 15:46 UTC, UkrainianCitizen commented on 1-js/02-first-steps/11-logical-operators/article.md
>      Це означає, що оператор `||` опрацьовує аргументи доти, доки не досягається перше правдиве значення, після чого це значення негайно повертається, без подальшого опрацювання решти аргументів.
@tarasyyyk **КРИТИЧНО**: який переклад для *truthy/falsy*? Тут усюдт вживається *truthy/falsy*. Потрібно якось розділяти *true/false* та *truthy/falsy*, в даному випадку, тут в оригіналі *truthy*, але переклад іде для *"true"*, що є неправильним.

2020-10-02 15:46 UTC, UkrainianCitizen commented on 1-js/02-first-steps/11-logical-operators/article.md
> +    Важливість цієї поведінки стає очевидною, коли операнд не проста змінна, а вираз з побічною дією, як от визначення змінної або виклик функції.
Дослівний переклад. 
~~коли операнд не проста змінна, а вираз з побічною дією, як от визначення змінної або виклик функції.~~ ->
```suggestion
    Важливість цієї поведінки стає очевидною, якщо операнд є не просто змінною, а виразом із побічним ефектом, як-от присвоєння змінної або виклик функції.
```
+1 питання до @tarasyyyk : side effect - побічна дія чи побічний ефект? Це треба теж в словник для консистентності. Я б переклав *ефект* поки що.

2020-10-02 15:46 UTC, UkrainianCitizen commented on 1-js/02-first-steps/11-logical-operators/article.md
> +alert( !!"непустий рядок" ); // true
"не пустий" якраз правильно. Я був би схильний написати просто "рядок", те, що він не пустий само собою зрозуміло.

2020-10-02 15:46 UTC, UkrainianCitizen commented on 1-js/02-first-steps/11-logical-operators/article.md
> +alert( Boolean("непустий рядок") ); // true
>"не пустий" якраз правильно. Я був би схильний написати просто "рядок", те, що він не пустий само собою зрозуміло.

2020-10-02 15:58 UTC, vsemozhetbyt commented on 1-js/02-first-steps/11-logical-operators/article.md
>  ````
«Зазвичай» на завжди є вставним словом и не завжди оточується комами. Приклади із словників:

 Про цей «страх статі», зазвичай притаманний усім тоталітарним формаціям, у XX столітті понаписувано чимало слушного й неслушного.. (Оксана Забужко, Хроніки від Фортінбраса, 2000).

Тритолуол — це потужна вибухова речовина, що зазвичай складається із тетрилу (75%) та толу (25%) (Сергій Жадан, Депеш Мод, 2004).

Витько – високий, худорлявий, короткозорий. Окуляри, однак, надівав тільки в гімназії, хоч зазвичай носив їх із собою повсякчас (Ю. Покальчук);

2020-10-02 16:07 UTC, vsemozhetbyt commented on 1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
> +# Який результат alerts, об'єднаних через І?
Без сполучників, мабуть, буде не дуже вдало, оскільки далі йде невідмінюване слово, що нагадує звичайний сполучник, і це заплутає читача.

2020-10-02 16:11 UTC, UkrainianCitizen commented on 1-js/02-first-steps/11-logical-operators/article.md
>  ````
Погоджуюся.

2020-10-02 16:11 UTC, vsemozhetbyt commented
@UkrainianCitizen Дякую за виправлення. Будь ласка, якщо вам не важко, оформлюйте їх відразу як готові пропозиції, тоді @tarasyyyk зможе одразу застосувати їх я коміти.

2020-10-02 16:16 UTC, UkrainianCitizen commented
Не зрозумів, що ви маєте на увазі під 
> готові пропозиції

2020-10-02 16:20 UTC, UkrainianCitizen commented on 1-js/02-first-steps/11-logical-operators/article.md
> +    Важливість цієї поведінки стає очевидною, коли операнд не проста змінна, а вираз з побічною дією, як от визначення змінної або виклик функції.
Я ще подивився в оригінал, там іде feature, а не behavior, тобто іде мова про всю фічу короткого замикання.

2020-10-02 16:28 UTC, vsemozhetbyt commented
Якщо ви натиснете кнопку, яку обведено червоним, в коментар будет вставлена пропозиція. Спочатку вона виглядає як повторення частини PR. Якщо ви зробите в ній виправлення, ваш коментар потім будет містити diff, який можна застосувати як коміт з виправленням цієї частини PR. Пропозицію может прийняти автор PR або будь-хто за правом запису в репозиторій.

![s](https://user-images.githubusercontent.com/10393198/94946540-fb4b4200-04e4-11eb-9495-17e25de1f352.png)
:

2020-10-02 16:34 UTC, UkrainianCitizen commented
Я зрозумів, так і думав, просто не бачив як його застосувати, хоча я контриб'ютор.

2020-10-02 16:45 UTC, vsemozhetbyt commented
Я чомусь теж не бачу тепер [інтерфейсу прийняття пропозицій](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes). Мабуть, це згубний наслідок того, що я видалив свій форк репозиторію, коли не зміг більше бути корисним проєкту. Мені шкода, якщо це так. Сподіваюсь, міни можна будет внести адміністратору при злитті PR. Якщо ні, тоді вони потребуватимуть нового PR. Вибачте(

2020-10-02 19:11 UTC, tarasyyyk commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Пріоритет НЕ `!` є найвищим з усіх логічних операторів, тому він завжди виконується першим, перед `&&` або `||`.
згоден щодо «серед усіх». Звучить краще

2020-10-02 19:19 UTC, tarasyyyk commented on 1-js/02-first-steps/11-logical-operators/article.md
> +Пріоритет оператора І `&&` вище за АБО `||`.
«Пріоритет оператора ... **вищий** за <оператор> АБО».
Мабуть так буде краще за **вище**.
Також можна перефразувати для кращого розуміння: «Оператор І `&&` має вищий пріоритет за АБО `||`».

2020-10-02 19:21 UTC, tarasyyyk commented on 1-js/02-first-steps/11-logical-operators/article.md
>      Це означає, що оператор `||` опрацьовує аргументи доти, доки не досягається перше правдиве значення, після чого це значення негайно повертається, без подальшого опрацювання решти аргументів.
Написав свою думку в [цьому коментарі](https://github.com/javascript-tutorial/uk.javascript.info/issues/8#issuecomment-702909880).

2020-10-02 19:30 UTC, tarasyyyk commented on 1-js/02-first-steps/11-logical-operators/article.md
> +    Важливість цієї поведінки стає очевидною, коли операнд не проста змінна, а вираз з побічною дією, як от визначення змінної або виклик функції.
Згоден щодо «побічного ефекту». «Побічна дія» більше для медицини підходить.

2020-10-02 19:50 UTC, UkrainianCitizen commented on 1-js/02-first-steps/11-logical-operators/article.md
> +    Важливість цієї поведінки стає очевидною, коли операнд не проста змінна, а вираз з побічною дією, як от визначення змінної або виклик функції.
[Тут ](https://services.ulif.org.ua/expl/Entry/index?wordid=26454&page=892)краще дивитися, ніж на Горосі, але тут до слова *обміль* на даний момент.

2020-10-02 20:17 UTC, vsemozhetbyt commented
@tarasyyyk Як ви порадите? Я не думав, що видалення форку унеможливить прийняття пропозицій, думав інтерфейсу GitHub буде достатньо, щоб внести можливі правки до PR. Я бачу два способи: або я закриваю всі свої реквести, роблю новий форк, копіюю туди файли з реквестів і відкриваю нові PR, де можна будет приймати поправки. Або хтось з колабораторів потім додасть поправки після  злиття цих проблемних реквестів. Перепрошую за незручності. Можливо, є простіші способи. Зрештою, можна взагалі проігнорувати всі ці мої PR і закрити їх, все одно в них лише купа дріб’язку, рано чи пізно всі слушні зміни хтось і так внесе.

2020-10-03 14:35 UTC, UkrainianCitizen commented
@vsemozhetbyt Зміни в ПР - відповідальність людини, котра його робить. Ви не мали видаляти форк in the first place, бо задача рев'ювера - лише рев'ювити. Робіть ПР із нового форку, а цей ПР, бажано з усіми коментами, зареференсіть в новому ПР. Так само зробіть із іншими ПР, які отримали рев'ю.

2020-10-03 14:52 UTC, vsemozhetbyt commented
Я не збирався не робити змін у відповідь на ревью, просто думав, що інтерфейс GitHub-у буде працювати і без форку. Тепер запам’ятаю, що ні.

В моїх минулих PR @tarasyyyk сам робив всі зміни за допомогою пропозицій і приймав їх сам перед злиттям. Мабуть, це теж дало мені помилокову надію.

Гаразд. Поки закриваю наявні, трохи пізніше зроблю нові.

2020-10-03 14:53 UTC, closed without merging

2020-10-03 15:37 UTC, vsemozhetbyt commented
PR на заміну з застосованими виправленнями: https://github.com/javascript-tutorial/uk.javascript.info/pull/119

Обидва інших PR також перевідкрив, але вони ще не мали ревью.