Functions
javascript-tutorial/uk.javascript.info pull request #127
Opened 2020-11-06 23:39 UTC by hypeofpipe

Привіт всім

Вибачаюсь за таку затримку, мої ГітХаб сповіщення були в відділі "спам", ха-ха, дякую Гугл.

Буду старатись переводити далі.

2020-11-06 23:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=127) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=127) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=127) it.</sub>

2020-11-07 10:22 UTC, tarasyyyk commented
Мені сподобався переклад коду та кометрарів! Чудово!

2020-11-07 10:43 UTC, tarasyyyk requested changes

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Досить часто ми потребуємо виконати подібну дію в багатьох місцях скрипту.
```suggestion
Досить часто нам потрібно виконати подібну дію в багатьох місцях скрипту.
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Функції це головні "будівні блоки" програми. Вони дозволяють робити ті самі дії багато разів в коді без повторення.
```suggestion
Функції це головні "будівельні блоки" програми. Вони дозволяють робити ті самі дії багато разів в коді без повторення.
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Ми вже зустрічались з такими вбудованими функціями, от-як `alert(message)`, `prompt(message, default)` і `confirm(question)`, але ми теж можемо творити свої функції.
```suggestion
Ми вже зустрічались з такими вбудованими функціями, як-от `alert(message)`, `prompt(message, default)` та `confirm(question)`. Але ми теж можемо створювати свої функції.
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +## Декларація (оголошення) Функцій
```suggestion
## Декларація (оголошення) функцій
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +І нарешті, код функції, також її називають _тілом функції_ між фігурними дужками. Функція може бути і без тіла, це Ви дізнаєтесь пізніше.
```suggestion
Спочатку ми пишемо `function` — це ключове слово (keyword), яке дає зрозуміти комп’ютеру, що далі буде оголошення функції. Потім — _назву функції_, тоді список її _параметрів_ в дужках (розділені комою). Якщо параметрів немає, ми залишаємо _пусті дужки_. І нарешті, код функції, який також називають _тілом функції_ між фігурними дужками. Функція може бути і без тіла, про це Ви дізнаєтесь пізніше.
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +І нарешті, код функції, також її називають _тілом функції_ між фігурними дужками. Функція може бути і без тіла, це Ви дізнаєтесь пізніше.
Цей текст повинен бути в одному рядку (23), щоб англійські та український переклади збігалися по рядках.

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Щоб викликати функцію, достатньо написати її ім'я і дужки: `showMessage()`
```suggestion
Щоб викликати функцію, достатньо написати її ім’я і дужки: `showMessage()`.
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Виклик функції `showMessage()` поводує виконання коду в тілі функції. В цьому прикладі ми побачимо, що функція два рази показує повідомлення.
```suggestion
Виклик функції `showMessage()` виконує код в тілі функції. В цьому прикладі ми побачимо, що функція два рази показує повідомлення.
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Цей приклад яскраво демонструє одну з найшоловніших цілей функції: уникання повторення коду.
```suggestion
Цей приклад яскраво демонструє одну з найголовніших цілей функції: уникнути повторення коду.
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Функція може використовувати зовнішні змінні, ось наприлад:
```suggestion
Функція може використовувати зовнішні змінні, ось наприклад:
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +alert( userName ); // *!*Бодя*/!*, після виклика функції showMessage. Змінна була змінена цієї функцією
```suggestion
alert( userName ); // *!*Бодя*/!*, значення було змінено після виклику функції showMessage
```

2020-11-07 10:43 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +// функція завжди віддасть переавгу локальним змінним
```suggestion
// функція завжди віддасть перевагу локальним змінним
```

2020-12-27 19:33 UTC, UkrainianCitizen commented on 1-js/02-first-steps/15-function-basics/article.md
> +Цей приклад яскраво демонструє одну з найшоловніших цілей функції: уникання повторення коду.
@tarasyyyk 
```suggestion
Цей приклад яскраво демонструє одну з найголовніших цілей функції - уникнення повторення коду.
```

2020-12-27 19:34 UTC, UkrainianCitizen commented on 1-js/02-first-steps/15-function-basics/article.md
> +## Локальні (місцеві) змінні
@tarasyyyk Local variables, по-моєму, немає в глосарії.

2020-12-27 19:35 UTC, UkrainianCitizen commented on 1-js/02-first-steps/15-function-basics/article.md
> -alert( message ); // <-- Error! The variable is local to the function
Чому *отакої*? *Error* - *Помилка*.

2020-12-27 20:04 UTC, UkrainianCitizen commented on 1-js/02-first-steps/15-function-basics/article.md
> +Виклик функції `showMessage()` поводує виконання коду в тілі функції. В цьому прикладі ми побачимо, що функція два рази показує повідомлення.
@tarasyyyk трішки підправив
```suggestion
Виклик `showMessage()` виконує код із тіла функції. В цьому випадку, ми побачимо повідомлення двічі.
```

2020-12-27 20:05 UTC, UkrainianCitizen commented on 1-js/02-first-steps/15-function-basics/article.md
> +Функції це головні "будівні блоки" програми. Вони дозволяють робити ті самі дії багато разів в коді без повторення.
Тире перед *це*

2020-12-28 18:41 UTC, hypeofpipe commented on 1-js/02-first-steps/15-function-basics/article.md
> -alert( message ); // <-- Error! The variable is local to the function
Старався розбавити текст від нудної літературної мови, але у кожного свій смак 👍

2020-12-28 18:43 UTC, hypeofpipe commented on 1-js/02-first-steps/15-function-basics/article.md
> -  *!*userName*/!* = "Bob"; // (1) changed the outer variable
Наведіть джерело, будь ласка, яке пітвердить, що Бодя – російське скорочення, цікаво

2020-12-28 18:44 UTC, hypeofpipe commented on 1-js/02-first-steps/15-function-basics/article.md
> +Якщо є дві змінні, одна - зовнішня, друга - локальна, тоді це називається _variable shadowing_, себто _затьмарення змінної_. Загалом це погана практика, але ось приклад, в якому локальна змінна `user
Обидві дефініції підходять ІМХО

2020-12-28 18:48 UTC, hypeofpipe commented on 1-js/02-first-steps/15-function-basics/article.md
> +  let message = 'Здоровенькі були, ' + *!*userName*/!*;
Старався розбавити текст від нудної літературної мови, але у кожного свій смак 👍

2020-12-28 19:29 UTC, UkrainianCitizen commented on 1-js/02-first-steps/15-function-basics/article.md
> -  *!*userName*/!* = "Bob"; // (1) changed the outer variable
@hypeofpipe нагуглив, схоже на те, що помилився, вікіпедія зазначає Бодя як скорочення, мені якось вилазили лише російські сайти із Бодя. В будь-якому випадку, це застосовується
> Власні назви не перекладаються

2021-02-22 18:09 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Зовнішня змінна використовується тоді, коли немає локальної (місцевої).
авжеж локальна.

2021-02-22 18:12 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +  let message = 'Здоровенькі були, ' + *!*userName*/!*;
> розбавити текст від нудної літературної мови

Мені це до вподоби!

2021-02-22 18:13 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> -alert( message ); // <-- Error! The variable is local to the function
Нехай буде "помилка".

2021-02-22 18:18 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +## Локальні (місцеві) змінні
додав.

2021-02-22 18:19 UTC, tarasyyyk commented
Привіт, @hypeofpipe !
Є прогрес з перекладом?

2021-07-13 19:13 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> +Якщо є дві змінні, одна - зовнішня, друга - локальна, тоді це називається _variable shadowing_, себто _затьмарення змінної_. Загалом це погана практика, але ось приклад, в якому локальна змінна `user
Додав `затьмарення`.

2021-07-13 19:54 UTC, tarasyyyk commented on 1-js/02-first-steps/15-function-basics/article.md
> -  *!*userName*/!* = "Bob"; // (1) changed the outer variable
Ви праві, @UkrainianCitizen, власні назви не перекладаються.
Однак в нашому посібнику не все так суворо і принципово. Ми не намагаємося перекласти його якнайбільш коректним і правильним відносно мовних правил. Все це робиться для звичайного користувача, якому немає великого діла до дуже коректного і офіційного українського тексту. Я згоден, що більшість користувачів зрозуміють хто такий "John" або "Bob", але погодьтеся, це виглядатиме трохи по-чужому для українського читача, аніж українські "Іван" та "Богдан".

2021-07-13 19:56 UTC, merged

2021-07-13 20:01 UTC, tarasyyyk commented
Виправив деякі конфлікти з гілкою `master` і злив даний PR в гілку `function-basics` (яка буде видала після закінчення перекладу). Продовжу переклад в #144.

2021-07-13 20:03 UTC, tarasyyyk commented
@all-contributors add @hypeofpipe for translation.