Map and Set translation
javascript-tutorial/uk.javascript.info pull request #148
Opened 2021-07-22 09:58 UTC by Regnised

Мова програмування JavaScript -> Data types -> Map i Set
My first translation!

2021-07-22 09:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=148) before we can accept your contribution.<br/><hr/>**Vasyl Onopriienko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=148) it.</sub>

2021-07-22 15:16 UTC, didostap commented
Дякую за чудовий переклад!

Помітив декілька граматичних помилок. Прожени, будь ласка, текст через цей [сервіс](https://ukr-mova.in.ua/perevirka-tekstu), щоб їх усіх одразу виявити.

2021-07-23 08:22 UTC, Regnised commented
Сподіваюсь переклад став кращим. Дякую за лінку на корисний в перекладі ресурс

2021-07-25 20:23 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +- `map.get(key)` -- повертає значення за ключем, повертає `undefined` якщо `key` не існує в колекції.
```suggestion
- `map.get(key)` -- повертає значення за ключем; повертає `undefined` якщо `key` немає в колекції.
```

2021-07-25 20:51 UTC, tarasyyyk requested changes
Дякую за переклад!
Декілька невеличких виправлень, і я заллю в основну гілку.

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +// пам'ятайте, звичайний об'єкт `Object` призводить ключі до рядків?
```suggestion
// пам’ятаєте звичайний об’єкт `Object`? Він перетворює всі ключі в рядок
```

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +Використання об'єктів як ключів -- це одна з відомих і часто застосовуваних можливостей колекції Map. Ми можемо використати ключі-рядки для об'єкта `Object`, але для ключів-об'єктів -- вже ні.
```suggestion
Об’єкти в якості ключів -- це одна з відомих можливостей колекції `Map`, яку часто використовують. У звичайному об’єкті `Object`, ми можемо використати ключі-рядки, проте ключі-об’єкти -- вже ні.
```

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +Спробуємо замінити Map на Object в прикладі вище::
```suggestion
Розгляньмо такий приклад:
```

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +visitsCountObj[ben] = 234; // використаємо `ben` об'єкт як ключ
```suggestion
visitsCountObj[ben] = 234; // використаємо об’єкт `ben` як ключ
```

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +let visitsCountObj = {}; // використаємо об'єкт
```suggestion
let visitsCountObj = {}; // оголосимо звичайний об’єкт
```

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +visitsCountObj[john] = 123; // використаємо `john` об'єкт як ключ, `ben` об'єкт буде перезаписаний
```suggestion
visitsCountObj[john] = 123; // використаємо об’єкт `john` як ключ. Об’єкт `ben` буде перезаписаний
```

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +// Ось як це було записано!
```suggestion
// Ось як це було записано рушієм!
```

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +Оскільки `visitsCountObj` -- це об'єкт, він конвертує всі ключі, такі як `john` і `ben`, до рядка `"[object Object]"`. Це однозначно не той результат, який ми очікуємо.
```suggestion
Оскільки `visitsCountObj` -- це об’єкт, він конвертує всі ключі типу `Object` (такі як `john` і `ben`) до рядка `"[object Object]"`. Це однозначно не той результат, який ми очікуємо.
```

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +['cucumber', 500],
додайте пробіли

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +```smart header="Як об'єкт `Map` порівнює ключі"
Не обов’язково явно вказувати, що `Map` -- це об’єкт. В такому випадку можна опустити слово `"об’єкт"`.
І ще замініть, будь ласка, всі одинарді лапки `'` на апостроф `’` у словах, де це потрібно (це легко можна зробити в текстовому рекакторі за допомогою функції «Знайти і замінити»).

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +alert(user.name); // John (тоді Pete і Mary)
пробіли

2021-07-25 20:51 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/article.md
> +## Висновок
"Підсумки"

2021-07-26 08:42 UTC, Regnised commented on 1-js/05-data-types/07-map-set/article.md
> +alert(user.name); // John (тоді Pete і Mary)
/done

2021-07-26 08:50 UTC, Regnised commented on 1-js/05-data-types/07-map-set/article.md
> +['cucumber', 500],
Done

2021-07-26 08:51 UTC, Regnised commented on 1-js/05-data-types/07-map-set/article.md
> +```smart header="Як об'єкт `Map` порівнює ключі"
Done

2021-07-26 08:51 UTC, Regnised commented on 1-js/05-data-types/07-map-set/article.md
> +## Висновок
Done

2021-07-26 09:09 UTC, Regnised commented
/done

2021-07-27 17:48 UTC, tarasyyyk commented on 1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
> +Наприклад:
```suggestion

Наприклад:
```

2021-07-27 17:50 UTC, tarasyyyk approved these changes

2021-07-27 17:50 UTC, merged

2021-07-27 18:06 UTC, tarasyyyk commented
@all-contributors add @Regnised for translation