WeakMap and WeakSet
javascript-tutorial/uk.javascript.info pull request #162
Opened 2021-07-28 23:58 UTC by MykolaSopiha

2021-07-29 17:15 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md
> +Інше, відмінне рішення може полягати у додавання властивості, як `message.ISRead=true` до повідомлення після його читання. Оскільки об’єкти повідомлень керуються іншим кодом, це, як правило, збентежу
```suggestion
Інше, відмінне рішення може полягати у додавання властивості, як `message.isRead=true` до повідомлення після його читання. Оскільки об’єкти повідомлень керуються іншим кодом, це, як правило, збентежує, але ми можемо використовувати символьну властивість, щоб уникнути конфліктів.
```

2021-07-29 17:17 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md
>  Like this:
```suggestion
Ось так:
```

2021-07-29 17:20 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/01-recipients-read/task.md
> +Тепер, яку б структуру даних могли б ви використовувати для зберігання інформації про те, чи було повідомлення прочитаним? Структура повинна добре підходити, щоб дати відповідь на питання "чи він про
```suggestion
Тепер, яку структуру даних ви могли б використати для зберігання інформації про те, чи було повідомлення прочитаним? Структура повинна добре підходити, щоб дати відповідь на питання "чи він прочитаний?" для об’єкта даного повідомлення.
```

2021-07-29 17:21 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/01-recipients-read/task.md
> +P.P.S. Ми не повинні змінювати об’єкти повідомлення, додавати на них наші властивості. Оскільки вони керуються іншим кодом, це може призвести до поганих наслідків.
```suggestion
P.P.S. Ми не повинні змінювати об’єкти повідомлення, додаючи до них наші властивості. Оскільки вони керуються іншим кодом, це може призвести до поганих наслідків.
```

2021-07-29 17:22 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/task.md
> +Зараз питання наступне: яку структура даних ви б запропонували для того, щоб зберегти інформацію: "Коли повідомлення було прочитано?".
```suggestion
Зараз питання наступне: яку структуру даних ви б запропонували для того, щоб зберегти інформацію: "Коли повідомлення було прочитано?".
```

2021-07-29 17:23 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/task.md
> +У попередньому завданні нам потрібно лише зберігати факт "так/ні". Тепер нам потрібно зберігати дату, і це повинно залишитися в пам’яті  лише доки повідомлення не буде видалено.
```suggestion
У попередньому завданні нам потрібно лише зберігати інформацію "так/ні". Тепер нам потрібно зберігати дату, і це повинно залишитися в пам’яті  лише доки повідомлення не буде видалено.
```

2021-07-29 17:42 UTC, tarasyyyk requested changes
Дуже добре. Є декілька невеличких правок. Я вже додав пропозиції, тож залишилося лише їх закомітити. На рахунок назв методів. Про це не переймайтеся – пізніше в англійському варіанті їх заберуть і я оновлю переклад.

2021-07-29 17:42 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/article.md
> +// ми можемо отримати його завдяки using map.keys()
```suggestion
// ми можемо отримати його, використовуючи map.keys()
```

2021-07-29 17:42 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/article.md
> +weakMap.set(obj, "ок"); // працює добре (об’єкт є ключем)
```suggestion
weakMap.set(obj, "ок"); // працює (об’єкт є ключем)
```

2021-07-29 17:42 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/article.md
> +Якщо ми працюємо з об’єктом, що "належить" до іншого коду, можливо навіть сторонньої бібліотеки, і хотіли б зберегти деякі дані, пов’язані з ним, що повинні існувати лише поки об’єкт живий -- тоді `W
```suggestion
Якщо ми працюємо з об’єктом, що "належить" до іншого коду, можливо навіть сторонньої бібліотеки, і хотіли б зберегти деякі дані, пов’язані з ним, що повинні існувати лише поки об’єкт живий -- тоді `WeakMap` цє саме те, що потрібно.
```

2021-07-29 17:42 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/article.md
> +Ми покладемо ці дані в `WeakMap`, використовуючи об’єкт як ключ, і коли об’єкт буде видалено збирачем сміття, то також дані автоматично зникнуть.
```suggestion
Ми покладемо дані в `WeakMap`, використовуючи об’єкт як ключ, і коли об’єкт буде видалено збирачем сміття, то ці дані також автоматично зникнуть.
```

2021-07-29 17:42 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/article.md
>  let john = { name: "John" };
```suggestion
let john = { name: "Іван" };
```

2021-07-29 17:42 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/article.md
>  alert(cache.size); // 1 (Ouch! The object is still in cache, taking memory!)
```suggestion
alert(cache.size); // 1 (Ой! Об’єкт досі в кеші і займає пам’ять!)
```

2021-07-29 17:42 UTC, tarasyyyk commented on 1-js/05-data-types/08-weakmap-weakset/article.md
> +`WeakMap` -- це подібна до `Map` колекція, яка дозволяє використовувати лише об’єктами, як ключі і видаляє їх разом з пов’язаним значенням, коли вони стануть недоступними іншим засобам.
```suggestion
`WeakMap` -- це подібна до `Map` колекція, яка дозволяє використовувати лише об’єкти, як ключі і видаляє їх разом з пов’язаним значенням, коли вони стануть недоступними іншим засобам.
```

2021-07-29 20:16 UTC, MykolaSopiha commented
@tarasyyyk дякую за правки! Я їх закомітив + додав ще пару невеликих фіксів. Сподіваюсь тепер все ок)

2021-08-01 12:27 UTC, MykolaSopiha commented
/done

2021-08-03 18:43 UTC, tarasyyyk commented
@MykolaSopiha чудово! Вибачте за затримку. Зараз в мене обмаль часу на перевірки.
Переклад підтверджую.

2021-08-03 18:46 UTC, tarasyyyk approved these changes

2021-08-03 18:46 UTC, merged