Objects
javascript-tutorial/uk.javascript.info pull request #192
Opened 2021-08-23 10:12 UTC by Regnised

Objects

2021-08-23 18:55 UTC, tarasyyyk commented on 1-js/05-data-types/05-array-methods/1-camelcase/task.md
> +Тобто дефіси видаляються, а всі слова після них починаються з великою літери.
```suggestion
Тобто дефіси видаляються, а всі слова після них починаються з великої літери.
```

2021-08-24 16:04 UTC, tarasyyyk requested changes
Дуже багато тексту перекладено. Щиро дякую за переклад!
Залишилось внести незначні зміни, і я заллю Ваш переклад

2021-08-24 16:04 UTC, tarasyyyk commented on 1-js/05-data-types/05-array-methods/7-map-objects/task.md
> +У вас є масив обʼєктів `user`, і у кожного з обʼєктів є `name`, `surname` та `id`.
```suggestion
У вас є масив обʼєктів `user`, і у кожного з обʼєктів є `name`, `surname` та `id`.
```
Не потрібно додавати пробіли в кінці рядків.
Будь ласка, використайте регулярний вираз `\s$`, щоб знайти всі пробіли в кінці рядків і замініть їх на `''`.

2021-08-24 19:01 UTC, Regnised commented on 1-js/05-data-types/05-array-methods/7-map-objects/task.md
> +У вас є масив обʼєктів `user`, і у кожного з обʼєктів є `name`, `surname` та `id`.
Добре

2021-08-24 19:37 UTC, Regnised reviewed
/done

2021-08-24 19:37 UTC, Regnised commented on 1-js/05-data-types/05-array-methods/12-reduce-object/task.md
>  let usersById = groupById(users);
Done

2021-08-24 19:38 UTC, Regnised commented
/done

2021-08-25 14:35 UTC, tarasyyyk commented on 1-js/05-data-types/05-array-methods/9-shuffle/solution.md
> +Результат прикладу (залежать від ядра JS):
```suggestion
Результат прикладу (залежить від рушія JS):
```

2021-08-25 14:35 UTC, tarasyyyk approved these changes

2021-08-25 14:36 UTC, merged