Function object, NFE
javascript-tutorial/uk.javascript.info pull request #198
Opened 2021-09-11 17:46 UTC by MykolaSopiha

2021-09-12 08:11 UTC, tarasyyyk requested changes

2021-09-12 08:11 UTC, tarasyyyk commented on 1-js/06-advanced-functions/06-function-object/article.md
>  function makeCounter() {
рядок 163: `// instead of:` можна теж перекласти: `// замість:`

2021-09-12 08:11 UTC, tarasyyyk commented on 1-js/06-advanced-functions/06-function-object/article.md
> +Наприклад, об'явімо звичайний Function Expression:
```suggestion
Наприклад, об’явімо звичайний Function Expression:
```

2021-09-12 08:11 UTC, tarasyyyk commented
Дякую за переклад! Декілька правок лишилось

2021-09-13 11:42 UTC, MykolaSopiha commented on 1-js/06-advanced-functions/06-function-object/article.md
>  A good way to imagine functions is as callable "action objects". We can not only call them, but also treat them as objects: add/remove properties, pass by reference etc.
Готово

2021-09-13 11:43 UTC, MykolaSopiha commented on 1-js/06-advanced-functions/06-function-object/article.md
>  function makeCounter() {
Готово

2021-09-13 13:25 UTC, tarasyyyk approved these changes

2021-09-13 13:25 UTC, merged

2021-09-13 13:25 UTC, tarasyyyk commented
Дякую за переклад!