Function binding
javascript-tutorial/uk.javascript.info pull request #203
Opened 2021-09-25 18:56 UTC by Vanchurick

2021-09-26 09:21 UTC, tarasyyyk commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/solution.md
> +Контекст прив'язаної функції жорстко-фіксований. Немає способу змінити це в подальшому.
```suggestion
Контекст прив’язаної функції жорстко-фіксований. Немає способу змінити це в подальшому.
```

2021-09-26 09:21 UTC, tarasyyyk commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
> +важливість: 5
```suggestion
importance: 5
```
Цей рядок не потрібно перекладати

2021-09-26 09:28 UTC, tarasyyyk requested changes

2021-09-26 09:28 UTC, tarasyyyk commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
> +# Прив'язана функція як метод
```suggestion
# Прив’язана функція як метод
```
Замініть, будь ласка, одинарні лапки `'` на апострофи `’`, де це необхідно.

2021-09-26 09:28 UTC, tarasyyyk commented on 1-js/06-advanced-functions/10-bind/3-second-bind/task.md
> +важливість: 5
```suggestion
importance: 5
```

2021-09-26 09:28 UTC, tarasyyyk commented on 1-js/06-advanced-functions/10-bind/3-second-bind/task.md
> +Чи можемо ми змінити `this` за допомогою додаткового прив'язування?
`'` => `’`

2021-09-26 09:28 UTC, tarasyyyk commented on 1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
> +1. Або використовуйте стрілкову функцію як функцію обгортку для короткого запису:
```suggestion
1. Або використовуйте стрілкову функцію, як функцію-обгортку для короткого запису:
```

2021-09-27 10:25 UTC, Vanchurick commented on 1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
> +1. Або використовуйте стрілкову функцію як функцію обгортку для короткого запису:
/done

2021-09-27 10:25 UTC, Vanchurick commented on 1-js/06-advanced-functions/10-bind/3-second-bind/task.md
> +Чи можемо ми змінити `this` за допомогою додаткового прив'язування?
/done

2021-09-27 10:26 UTC, Vanchurick commented on 1-js/06-advanced-functions/10-bind/3-second-bind/task.md
> +важливість: 5
/done

2021-09-27 10:26 UTC, Vanchurick commented on 1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
> +# Прив'язана функція як метод
/done

2021-09-27 10:26 UTC, Vanchurick commented
/done

2021-09-30 17:57 UTC, tarasyyyk commented on 1-js/06-advanced-functions/10-bind/article.md
> +setTimeout(f, 1000); // втрата контексту об`єкта user
```suggestion
setTimeout(f, 1000); // втрата контексту об’єкта user
```

2021-09-30 17:59 UTC, tarasyyyk commented on 1-js/06-advanced-functions/10-bind/article.md
> +## Висновок
```suggestion
## Підсумки
```

2021-09-30 18:00 UTC, tarasyyyk approved these changes

2021-09-30 18:02 UTC, merged

2021-09-30 18:02 UTC, tarasyyyk commented
Чудовий переклад! Дякую!
@all-contributors add @Vanchurick for translation.