1-js/06-advanced-functions/03-closure
javascript-tutorial/uk.javascript.info pull request #219
Opened 2021-11-14 00:07 UTC by stas-dolgachov

Повний переклад розділу і задач

2021-11-14 14:12 UTC, tarasyyyk requested changes
Велика Подяка за такий чудовий переклад! Взагальному все чудово, потрібно зробити лише декілька виправлень. Дякую!
До файлів `svg` я не дивився, сподіваюся там все добре.

2021-11-14 14:12 UTC, tarasyyyk commented on 1-js/06-advanced-functions/03-closure/article.md
> +// Три функції в масиві, кожна з яких пов’язана з лексичним середовищем
```suggestion
// три функції в масиві, кожна з яких пов’язана з лексичним середовищем
```

2021-11-14 14:12 UTC, tarasyyyk commented on 1-js/06-advanced-functions/03-closure/closure-function-declaration.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="678" height="169" viewBox="0 0 678 169"><defs><style>@import url(https://fonts.googleapis.com/css?family=Open+Sans:bold,italic,bolditalic%7CPT+Mono);@fo
в цьому файлі щось змінювалося?

2021-11-14 14:12 UTC, tarasyyyk commented on 1-js/06-advanced-functions/03-closure/3-counter-independent/solution.md
>  The answer: **0,1.**
```suggestion
Відповідь: **0,1.**
```

2021-11-14 19:42 UTC, stas-dolgachov commented on 1-js/06-advanced-functions/03-closure/closure-function-declaration.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="678" height="169" viewBox="0 0 678 169"><defs><style>@import url(https://fonts.googleapis.com/css?family=Open+Sans:bold,italic,bolditalic%7CPT+Mono);@fo
Там було перекладено одну фразу, але я повернув як було =)

2021-11-14 19:42 UTC, stas-dolgachov commented
/done

2021-11-15 17:25 UTC, tarasyyyk commented on 1-js/06-advanced-functions/03-closure/2-closure-variable-access/task.md
>  let name = "John";
```suggestion
let name = "Іван";
```

2021-11-15 17:25 UTC, tarasyyyk commented on 1-js/06-advanced-functions/03-closure/2-closure-variable-access/task.md
> +Яке значення вона покаже? "Pete" чи "John"?
```suggestion
Яке значення вона покаже? "Петро" чи "Іван"?
```

2021-11-15 17:29 UTC, tarasyyyk approved these changes

2021-11-15 17:30 UTC, merged

2022-05-29 06:28 UTC, Lozitsky commented
Хочу внести зміни в приклад, який не працює: https://github.com/javascript-tutorial/uk.javascript.info/blob/master/1-js/06-advanced-functions/03-closure/9-sort-by-field/_js.view/solution.js
На тестах перевірив.