Async/await
javascript-tutorial/uk.javascript.info pull request #221
Opened 2021-11-18 13:48 UTC by Nordtonito

2021-11-18 13:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=221) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=221) before we can accept your contribution.<br/><hr/>**Vitalii_Nesteruk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=221) it.</sub>

2021-11-22 12:25 UTC, tarasyyyk requested changes

2021-11-22 12:25 UTC, tarasyyyk commented on 1-js/11-async/08-async-await/01-rewrite-async/solution.md
> +Примітки:
```suggestion

Примітки:
```

2021-11-22 12:25 UTC, tarasyyyk commented on 1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
> +    let name = prompt("Введіть ім'я?", "iliakan");
```suggestion
    let name = prompt("Введіть ім’я?", "iliakan");
```

2021-11-22 12:25 UTC, tarasyyyk commented on 1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
> +  alert(`Повне ім'я: ${user.name}.`);
```suggestion
  alert(`Ім’я та прізвище: ${user.name}.`);
```

2021-11-22 12:25 UTC, tarasyyyk commented on 1-js/11-async/08-async-await/02-rewrite-async-2/task.md
> +І позбудьтеся від рекурсії на користь циклу в `demoGithubUser`: за допомогою `async/await` зробити це буде легко.
```suggestion
І позбудьтеся від рекурсії на користь циклу в `demoGithubUser`: за допомогою `async/await` це буде легко зробити.
```

2021-11-22 12:25 UTC, tarasyyyk commented on 1-js/11-async/08-async-await/02-rewrite-async-2/task.md
> +  let name = prompt("Введіть ім'я?", "iliakan");
```suggestion
  let name = prompt("Введіть ім’я?", "iliakan");
```

2021-11-22 12:25 UTC, tarasyyyk commented on 1-js/11-async/08-async-await/02-rewrite-async-2/task.md
> +      alert(`Повне ім'я: ${user.name}.`);
```suggestion
      alert(`Ім’я та прізвище: ${user.name}.`);
```

2021-11-22 12:25 UTC, tarasyyyk commented on 1-js/11-async/08-async-await/article.md
> +...Ми могли б явно повернути проміс, результат буде таким же:
```suggestion
...Ми могли б явно повернути проміс, результат буде таким самим:
```
https://onlinecorrector.com.ua/uk/той-самий/

2021-11-22 12:25 UTC, tarasyyyk commented on 1-js/11-async/08-async-await/article.md
> +Підкреслимо: `await` буквально призупиняє виконання функції до тих пір, поки проміс не виконається, а потім відновлює її з результатом проміса. Це не вимагає жодних ресурсів ЦП, тому що движок JavaSc
```suggestion
Підкреслимо: `await` буквально призупиняє виконання функції до тих пір, поки проміс не виконається, а потім відновлює її з результатом проміса. Це не вимагає жодних ресурсів ЦП, тому що рушій JavaScript може тим часом робити інші завдання: виконувати інші скрипти, обробляти події тощо.
```

2021-11-22 18:40 UTC, Nordtonito commented on 1-js/11-async/08-async-await/article.md
> +Підкреслимо: `await` буквально призупиняє виконання функції до тих пір, поки проміс не виконається, а потім відновлює її з результатом проміса. Це не вимагає жодних ресурсів ЦП, тому що движок JavaSc
Виправлено, дякую!

2021-11-22 18:40 UTC, Nordtonito commented on 1-js/11-async/08-async-await/article.md
> +...Ми могли б явно повернути проміс, результат буде таким же:
Виправлено, дякую!

2021-11-22 18:40 UTC, Nordtonito commented on 1-js/11-async/08-async-await/02-rewrite-async-2/task.md
> +      alert(`Повне ім'я: ${user.name}.`);
Виправлено, дякую!

2021-11-22 18:40 UTC, Nordtonito commented on 1-js/11-async/08-async-await/02-rewrite-async-2/task.md
> +  let name = prompt("Введіть ім'я?", "iliakan");
Виправлено, дякую!

2021-11-22 18:41 UTC, Nordtonito commented on 1-js/11-async/08-async-await/02-rewrite-async-2/task.md
> +І позбудьтеся від рекурсії на користь циклу в `demoGithubUser`: за допомогою `async/await` зробити це буде легко.
Виправлено, дякую!

2021-11-22 18:41 UTC, Nordtonito commented on 1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
> +  alert(`Повне ім'я: ${user.name}.`);
Виправлено, дякую!

2021-11-22 18:41 UTC, Nordtonito commented on 1-js/11-async/08-async-await/02-rewrite-async-2/solution.md
> +    let name = prompt("Введіть ім'я?", "iliakan");
Виправлено, дякую!

2021-11-22 18:41 UTC, Nordtonito commented on 1-js/11-async/08-async-await/01-rewrite-async/solution.md
> +Примітки:
Виправлено, дякую!

2021-11-22 18:41 UTC, Nordtonito commented
/done

2021-11-22 19:17 UTC, tarasyyyk commented
@Nordtonito ще підпишіть, будь ласка, license/cla

2021-11-22 23:24 UTC, Nordtonito commented
/done

2021-11-23 09:00 UTC, Nordtonito commented
@tarasyyyk ніби владнав всі питання - заапрувте, як буде можливість, будь ласка

2021-11-23 16:14 UTC, tarasyyyk approved these changes
Все добре. Дякую за переклад!

2021-11-23 16:14 UTC, merged