Error handling, "try...catch"
javascript-tutorial/uk.javascript.info pull request #225
Opened 2021-12-04 23:18 UTC by Purusah

2021-12-04 23:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=225) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=225) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=225) it.</sub>

2021-12-06 12:16 UTC, tarasyyyk requested changes
Дякую за переклад.
Дуже багато тексту було перекладено!
Залишилось декілька виправлень перед зляттям в основну гілку.

2021-12-06 12:16 UTC, tarasyyyk commented on 1-js/10-error-handling/1-try-catch/article.md
> +На скільки чудовими програмістами ми б не були, але часом трапляється, що в роботі наших скрипів можуть виникати виключні ситуації. Вони виникають через наші помилки, непередбачувані вхідні дані від
```suggestion
Якими чудовими програмістами ми б не були, часом трапляється, що в наших скриптах виникають помилки. Вони можуть виникнути через нашу неуважність, непередбачувані вхідні дані від користувачів, неправильні відповіді від сервера або з тисяч інших причин.
```

2021-12-06 12:16 UTC, tarasyyyk commented on 1-js/10-error-handling/1-try-catch/article.md
> +2. Якщо не виникає помилок, то блок `catch (err)` ігнорується: виконання досягає кінця блоку `try` та продовжується поза `catch` блоком.
```suggestion
2. Якщо не виникає помилок, то блок `catch (err)` ігнорується: виконання досягає кінця блоку `try` та продовжується поза блоком `catch`.
```

2021-12-06 12:16 UTC, tarasyyyk commented on 1-js/10-error-handling/1-try-catch/article.md
> +3. Якщо виникає помилка, тоді виконання в `try` припиняється і виконання коду продовжується з початку `catch (err)` блоку. Змінна `err` (можна обрати інше ім’я) буде містити об’єкт помилки з додатков
```suggestion
3. Якщо виникає помилка, тоді виконання в `try` припиняється і виконання коду продовжується з початку блоку `catch (err)`. Змінна `err` (можна обрати будь-яке ім’я) буде містити об’єкт помилки з додатковою інформацією.
```

2021-12-06 12:16 UTC, tarasyyyk commented on 1-js/10-error-handling/1-try-catch/article.md
> +      alert('Початок try блоку');  // *!*(1) <--*/!*
Замініть, будь ласка, порядок таких слів в коді.
Має бути: блок `try`

2021-12-06 12:16 UTC, tarasyyyk commented on 1-js/10-error-handling/1-try-catch/article.md
> +Наприклад:
Тут номери рядків «розбігаються»

2021-12-06 20:45 UTC, Purusah commented
Дякую!
Додав зміни, виправив порядок слів на "блок `try`"

2021-12-06 20:45 UTC, Purusah commented
/done

2021-12-07 09:41 UTC, tarasyyyk approved these changes
Дякую за переклад!

2021-12-07 09:42 UTC, tarasyyyk commented
@all-contributors add @Purusah for translation.

2021-12-07 09:45 UTC, merged