Strings
javascript-tutorial/uk.javascript.info pull request #230
Opened 2021-12-09 13:51 UTC by gingano

Strings

2021-12-09 17:54 UTC, gingano commented
> Error: the article has another translator @gingano) [_translation requested_]([#1 (comment)](https://github.com/javascript-tutorial/uk.javascript.info/issues/1#issuecomment-883956228) in the Progress Issue #1.

@tarasyyyk it's ok ?

2021-12-12 14:11 UTC, tarasyyyk requested changes
Дуже об’ємний переклад! Дякую за старання!
Я додав декілька правок

2021-12-12 14:11 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Внутрішній формат для рядків завжди [UTF-16](https://en.wikipedia.org/wiki/UTF-16), він не прив'язаний до кодування сторінки.
```suggestion
Внутрішній формат для рядків завжди [UTF-16](https://uk.wikipedia.org/wiki/UTF-16), він не прив’язаний до кодування сторінки.
```

2021-12-12 14:11 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Одинарні та подвійні лапки беруть свій початок з давніх часів створення мови, коли потреба у багатолінійних рядках не враховувалась. Зворотні лапки з'явилися набагато пізніше і тому є більш універсал
```suggestion
Одинарні та подвійні лапки беруть свій початок з давніх часів створення мови, коли потреба у багатолінійних рядках не враховувалась. Зворотні лапки з’явилися набагато пізніше і тому є більш універсальними.
```
Замініть одинарні лапки (`'`) на апострофи (`’`) по всьому тексту (де це потрібно).

2021-12-12 14:11 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
>  let guestList = "Guests:\n * John\n * Pete\n * Mary";
```suggestion
let guestList = "Гості:\n * Іван\n * Петро\n * Марія";
```

2021-12-12 14:11 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +let str1 = "Hello\nWorld"; // дві лінії з використанням "символу нового рядка"
```suggestion
let str1 = "Привіт\nСвіт"; // дві лінії з використанням "символу нового рядка"
```

2021-12-12 14:11 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Рядок в JavaScript незмінний. Не можна змінити символ в рядку.
Непотрібний рядок

2021-12-15 08:34 UTC, gingano commented on 1-js/05-data-types/03-string/article.md
> +Одинарні та подвійні лапки беруть свій початок з давніх часів створення мови, коли потреба у багатолінійних рядках не враховувалась. Зворотні лапки з'явилися набагато пізніше і тому є більш універсал
Пройшовся пошуком по всім одинарним лапкам, де потрібно – змінив на апострофи

2021-12-15 08:41 UTC, gingano commented
/done

2021-12-17 17:46 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/3-truncate/_js.view/test.js
> +  it("Не змінює короткі рядки", function() {
```suggestion
  it("не змінює короткі рядки", function() {
```

2021-12-17 17:47 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +  alert(char); // H,e,l,l,o (char — спочатку "H", потім "e", потім "l" і т. д.)
```suggestion
  alert(char); // H,e,l,l,o (char — спочатку "H", потім "e", потім "l" тощо)
```

2021-12-17 17:48 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +  alert( `Знайтено тут: ${foundPos}` );
```suggestion
  alert( `Знайдено тут: ${foundPos}` );
```

2021-12-17 17:49 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Той сами алгоритм можна записати коротше:
```suggestion
Той самий алгоритм можна записати коротше:
```

2021-12-17 17:50 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Такоє є схожий метод [str.lastIndexOf(substr, position)](mdn:js/String/lastIndexOf), що виконує пошук від кінця рядка до його початку.
```suggestion
Також є схожий метод [str.lastIndexOf(substr, position)](mdn:js/String/lastIndexOf), що виконує пошук від кінця рядка до його початку.
```

2021-12-17 17:52 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +`alert` у наведеному вище прикладі не відображається, оскільки `str.indexOf("Widget")` повертає `0` (це означає, що він знайшов збіг у початковій позиції). Правильно, але `if` вважає, що `0` -- це `f
```suggestion
В прикладі вище `alert` не відображається, оскільки `str.indexOf("Widget")` повертає `0` (це означає, що він знайшов збіг у початковій позиції). Це правильно, але `if` вважає, що `0` -- це `false`.
```

2021-12-17 17:54 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Один із старих прийомів, який використовуються тут, це [побітовий оператор НЕ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT) -- `~`. Він перетворює число в
```suggestion
Один із старих прийомів, який використовується тут, це [побітовий оператор НЕ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT) -- `~`. Він перетворює число в 32-розрядне ціле число (вилучає десяткову частину, якщо вона є), а потім повертає всі біти в його двійковому представленні.
```

2021-12-17 18:23 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Просто запамʼятайте: `if (~str.indexOf(...))` означає "якщо знайдено"
```suggestion
Просто запамʼятайте: `if (~str.indexOf(...))` означає "якщо знайдено".
```

2021-12-17 18:27 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Більш сучасний мето [str.includes(substr, pos)](mdn:js/String/includes) повертає `true/false` в залежності від того чи є в рядку `str` підрядок `substr`.
```suggestion
Сучасніший метод [str.includes(substr, pos)](mdn:js/String/includes) повертає `true/false` в залежності від того чи є в рядку `str` підрядок `substr`.
```

2021-12-17 18:29 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Це -- правильний вибір, якщо потріно перевірити чи є збіг, але не потрібна позиція:
```suggestion
Цей метод доцільно використовувати, коли потрібно перевірити чи є збіг, але не потрібна позиція:
```

2021-12-17 18:31 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Необовʼязковий другий аргумент `str.includes` це позиція з якої почнеться пошук:
```suggestion
Необовʼязковий другий аргумент `pos` -- це позиція з якої почнеться пошук:
```

2021-12-17 18:32 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +alert( "Widget".includes("id", 3) ); // false, починаючи з позиції 3 підрядка "id" немає
```suggestion
alert( "Widget".includes("id", 3) ); // false, починаючи з 3-го символа, підрядка "id" немає
```

2021-12-17 18:32 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Методи [str.startsWith](mdn:js/String/startsWith) та [str.endsWith](mdn:js/String/endsWith) перевіряють, відповідно, чи починається і чи закінчується рядок певним підрядком.
```suggestion
Відповідно, методи [str.startsWith](mdn:js/String/startsWith) та [str.endsWith](mdn:js/String/endsWith) перевіряють, чи починається і чи закінчується рядок певним підрядком.
```

2021-12-17 18:35 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +    Також для `start/end` можна задати відʼємне значення. Це означає, що позиція визначена як задана кількість символів з кінця рядка:
```suggestion
    Також для `start/end` можна задати відʼємне значення. Це означає, що позиція буде рахуватися з кінця рядка:
```

2021-12-17 18:37 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +    // починаємо з позиції 4 справа, а закінчуємо на позиції 1 справа
```suggestion
    // починаємо з 4-го символа справа, і закінчуємо на 1-му символі справа
```

2021-12-17 18:38 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +    alert( str.slice(6, 2) ); // "" (пустий рядок)
```suggestion
    alert( str.slice(6, 2) ); // "" (порожній рядок)
```

2021-12-17 18:43 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Отже, браузеру потрібно зната, яку мову використовувати для порівняння
```suggestion
Отже, браузеру потрібно знати, яку мову використовувати для порівняння
```

2021-12-17 18:45 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +Цей метод насправді має два додаткові аргументи, зазначені в [документації](mdn:js/String/localeCompare), що дозволяє йому вказати мову (за замовчуванням взяту з середовища, порядок букв залежить від
```suggestion
Цей метод насправді має два додаткові аргументи, зазначені в [документації](mdn:js/String/localeCompare), що дозволяє йому вказати мову (типово взяту з середовища, порядок букв залежить від мови) і встановити додаткові правила, як-от чутливість до регістру або чи слід розглядати різницю між `"a"` та `"á"`.
```

2021-12-17 18:51 UTC, tarasyyyk commented on 1-js/05-data-types/03-string/article.md
> +- Щоб перевисти рядок у нижній/верхній регістри, використовуйте: `toLowerCase/toUpperCase`.
```suggestion
- Щоб перевести рядок у нижній/верхній регістри, використовуйте: `toLowerCase/toUpperCase`.
```

2021-12-17 20:04 UTC, tarasyyyk approved these changes
Нарешті переклад цієї величезної статті завершено!
Велике Спасибі!

2021-12-17 20:06 UTC, tarasyyyk commented
@gingano, залишилось підписати [CLA](https://github.com/javascript-tutorial/uk.javascript.info/pull/230#issuecomment-989871063).

2021-12-18 12:49 UTC, gingano commented
@tarasyyyk підписав, можеш мерджити

2021-12-18 18:04 UTC, tarasyyyk commented
@all-contributors add @gingano for translation.

2021-12-18 18:06 UTC, tarasyyyk approved these changes

2021-12-18 18:07 UTC, merged