Error handling with promises
javascript-tutorial/uk.javascript.info pull request #231
Opened 2021-12-10 14:09 UTC by AntonBurchak

2021-12-10 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=231) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=231) before we can accept your contribution.<br/><hr/>**Anton_Burchak** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=231) it.</sub>

2021-12-12 14:19 UTC, tarasyyyk requested changes

2021-12-12 14:19 UTC, tarasyyyk commented on 1-js/11-async/04-promise-error-handling/01-error-async/solution.md
> +Як було сказано в главі, тут присутній "прихований `try..catch`" навколо коду функції. Тому обробляються усі синхронні помилки.
```suggestion

Як було написано в розділі, тут присутній "прихований `try..catch`" навколо коду функції. Тому обробляються усі синхронні помилки.
```

2021-12-12 14:19 UTC, tarasyyyk commented on 1-js/11-async/04-promise-error-handling/01-error-async/task.md
> +```
Не зрозуміло, чому рядок виділяється як змінений. По тексту ніби нічого не мінялося

2021-12-12 14:19 UTC, tarasyyyk commented on 1-js/11-async/04-promise-error-handling/article.md
> +Як можна побачити, `.catch` не обов'язково повинен бути відразу після помилки, він може бути далі, після одного або навіть декількох `.then`.
```suggestion
Як можна побачити, `.catch` не обов’язково повинен бути відразу після помилки, він може бути далі, після одного або навіть декількох `.then`.
```
Замініть по тексту одинарні лапки (`'`) на апострофи (`’`) (де це потрібно)

2021-12-12 14:19 UTC, tarasyyyk commented on 1-js/11-async/04-promise-error-handling/article.md
> +Приклад:
```suggestion
Приклад:
```

2021-12-12 14:19 UTC, tarasyyyk commented on 1-js/11-async/04-promise-error-handling/article.md
>  ## Summary
```suggestion
## Підсумки
```

2021-12-13 13:12 UTC, AntonBurchak commented
/done

2021-12-13 13:14 UTC, AntonBurchak commented
@tarasyyyk review it again, please

2021-12-13 19:04 UTC, tarasyyyk approved these changes

2021-12-13 19:05 UTC, merged

2021-12-13 19:05 UTC, tarasyyyk commented
@all-contributors add @AntonBurchak for translation.