Export and Import
javascript-tutorial/uk.javascript.info pull request #242
Opened 2021-12-26 19:17 UTC by Purusah

Translated Export and Import

2021-12-27 12:42 UTC, tarasyyyk commented on 1-js/13-modules/02-import-export/article.md
> +## Експорт за замовчуванням
```suggestion
## Типовий експорт (export default)
```

2021-12-27 12:43 UTC, tarasyyyk commented on 1-js/13-modules/02-import-export/article.md
> +| Іменований експорт | Експорт за замовчуванням |
```suggestion
| Іменований експорт | Типовий експорт |
```

2021-12-27 12:43 UTC, tarasyyyk commented on 1-js/13-modules/02-import-export/article.md
> +Технічно, ми можемо використовувати іменовані експорти та експорти за замовчуванням в одному модулі, але, на практиці, їх не прийнято змішувати. Модулі повинні мати або іменований експорт, або за зам
```suggestion
Технічно, ми можемо використовувати іменовані експорти та типові експорти в одному модулі, але, на практиці, їх не прийнято змішувати. Модулі повинні мати або іменований експорт, або типовий.
```

2021-12-27 12:45 UTC, tarasyyyk requested changes

2021-12-27 12:45 UTC, tarasyyyk commented on 1-js/13-modules/02-import-export/article.md
> +export class { // Помилка! (експорт за замовчування потребує імені)
```suggestion
export class { // Помилка! (типовий експорт потребує імені)
```
Будь ласка, замініть "експорт за замовчеванням" на "типовий експорт"

2021-12-27 18:39 UTC, Purusah commented on 1-js/13-modules/02-import-export/article.md
> +export class { // Помилка! (експорт за замовчування потребує імені)
Замінив всі "за замовчуванням" на "типовий"

2021-12-27 18:39 UTC, Purusah commented
/done

2021-12-28 07:51 UTC, tarasyyyk approved these changes

2021-12-28 07:52 UTC, merged