Feature/introduction browser events
javascript-tutorial/uk.javascript.info pull request #292
Opened 2022-01-25 13:11 UTC by Regnised

Introduction to browser events

2022-01-28 21:45 UTC, stas-dolgachov requested changes

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
> +# Який обробник запуститься?
```suggestion
# Який обробник буде запущено?
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
> +Який з обробників запуститься? Що буде виведено під час кліку після виконання коду?
```suggestion
Який обробник буде запущено? Що буде виведено під час кліку після виконання коду?
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +Ми не можемо використати `position:fixed` для цього, оскільки прокручування сторінки переміщатиме м’яч поля.
```suggestion
Ми не можемо використати `position:fixed` для цього, оскільки прокручування сторінки переміщатиме м’яч від поля.
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +Далі ми маємо призначити коректні значення `ball.style.left/top`. Зараз вони містять координати щодо поля.
```suggestion
Далі ми маємо призначити коректні значення `ball.style.left/top`. Зараз вони містять координати відносно поля.
```
Здається, що так краще, як вважаєте?

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +Тоді м’яч буде позиціонований щодо поля:
```suggestion
Тоді м’яч буде позиціонований відносно поля:
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +Щоб отримати значення `left` для м’яча після натискання мишки щодо поля, ми повинні від координати натискання мишки відняти координату лівого краю поля та ширину межі:
```suggestion
Щоб отримати значення `left` для м’яча після натискання мишки відносно поля, ми повинні від координати натискання мишки відняти координату лівого краю поля та ширину межі:
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +Значення `ball.style.left` означає «лівий край елемента» (м’яча). І якщо ми призначимо такий `left` для м’яча, то його ліва межа, а не центр, буде під курсором миші.
```suggestion
Значення `ball.style.left` означає "лівий край елемента" (м’яча). І якщо ми призначимо такий `left` для м’яча, то його ліва межа, а не центр, буде під курсором миші.
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +Нам потрібно зрушити м'яч на половину його висоти вгору та половину його ширини вліво, щоб центр м’яча точно збігався з точкою натискання мишки.
```suggestion
Нам потрібно зрушити м’яч на половину його висоти вгору та половину його ширини вліво, щоб центр м’яча точно збігався з точкою натискання мишки.
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +У результаті значення для `left` буде таким:
```suggestion
В результаті значення для `left` буде таким:
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
> +Вертикальна координата обчислюватиметься за тією ж логікою.
```suggestion
Вертикальна координата обчислюється за тією ж логікою.
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.view/index.html
> +  Натисніть поле, щоб перемістити м’яч.
```suggestion
  Клікнить по полю, щоб перемістити м’яч.
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.view/index.html
> +      // координати поля щодо вікна браузера
```suggestion
      // координати поля відносно вікна браузера
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.view/index.html
> +      // м’яч має абсолютне позиціювання (position:absolute), поле - відносне (position:relative)
```suggestion
      // м’яч має абсолютне позиціювання (position:absolute), поле -- відносне (position:relative)
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.view/index.html
> +      // таким чином, координати м’яча розраховуються щодо внутрішнього, верхнього лівого кута поля.
```suggestion
      // таким чином, координати м’яча розраховуються відносно внутрішнього, верхнього лівого кута поля.
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
> +важливість: 5
```suggestion
importance: 5
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
> +Нехай м’яч переміщається при натисканні на поле, туди, куди був клік, ось так:
```suggestion
Нехай м’яч переміщається при натисканні на поле, туди, де був клік, ось так:
```

2022-01-28 21:45 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
> +- Код повинен уміти працювати з різними розмірами м'яча та поля, не прив’язуватися до будь-яких фіксованих значень.
```suggestion
- Код повинен уміти працювати з різними розмірами м’яча та поля, не прив’язуватися до будь-яких фіксованих значень.
```

2022-01-28 21:50 UTC, stas-dolgachov commented
@Regnised Дякую за чудовий переклад величезної статті! 
Я подивився його лише частково, згодом завершу ;)

2022-01-31 15:02 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/07-carousel/solution.md
> +Потрібно розташувати стрічку всередині `<div>` фіксованого розміру, так щоб одночасно була видна тільки потрібна частина списку:
```suggestion
Потрібно розташувати стрічку всередині `<div>` фіксованого розміру, так щоб одночасно було видно тільки потрібну частину списку:
```

2022-01-31 15:06 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/07-carousel/task.md
> +важливість: 4
```suggestion
importance: 4
```

2022-01-31 15:09 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Події можна призначити обробник, тобто функцію, яка спрацює, щойно подія сталася.
```suggestion
Події можна призначити обробник, тобто функцію, яка виконається, щойно подія сталася.
```
Здається так краще, але невпевнений

2022-01-31 15:12 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Наприклад, щоб призначити обробник події `click` на елементі `input`, можна використовувати атрибут `onclick`, ось так:
```suggestion
Наприклад, щоб призначити обробник події `click` на елементі `input`, можна використати атрибут `onclick`, ось так:
```

2022-01-31 15:20 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +У першому прикладі використовувався атрибут HTML для ініціалізації `button.onclick`, тоді як у другому прикладі -- сценарій, ось і вся різниця.
```suggestion
У першому прикладі використовувався атрибут HTML для ініціалізації `button.onclick`, тоді як у другому прикладі -- код зі скрипта, ось і вся різниця.
```

2022-01-31 15:22 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Якщо ви починаєте працювати з подіями, зверніть увагу на наступні моменти.
```suggestion
Якщо ви починаєте працювати з подіями, зверніть увагу на наступні нюанси.
```

2022-01-31 15:26 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Використовуйте `elem.onclick`, а не `elem.ONCLICK`, тому що DOM-властивості чутливі до регістру.
```suggestion
Використовуйте `elem.onclick`, а не `elem.ONCLICK`, тому що властивості DOM-вузлів чутливі до регістру.
```

2022-01-31 15:26 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Фундаментальний недолік описаних вище способів присвоєння обробника -- неможливість повісити кілька обробників для однієї події.
```suggestion
Фундаментальний недолік описаних вище способів -- неможливість додати декілька обробників для однієї події.
```

2022-01-31 15:27 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +    - `capture`: фаза, на якій повинен спрацювати обробник, докладніше про це буде розказано у розділі <info:bubbling-and-capturing>. Так історично склалося, що `options` може бути `false/true`, це т
```suggestion
    - `capture`: фаза, на якій повинен спрацювати обробник, докладніше про це буде розказано у розділі <info:bubbling-and-capturing>. Так історично склалося, що `options` може бути `false/true`, це те саме, що й `{capture: false/true}`.
```

2022-01-31 15:28 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +````warn header="Видалення підписника на подію вимагає саме ту ж функцію"
```suggestion
````warn header="Видалення обробника на подію вимагає саме ту ж функцію"
```

2022-01-31 15:29 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Для видалення потрібно передати саме ту функцію-обробник, яка була присвоєна.
```suggestion
Для видалення потрібно передати саме ту функцію-обробник, яку було використано при додаванні.
```

2022-01-31 15:29 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Обробник не буде видалено, так як `removeEventListener` передано не таку ж функцію, а іншу, з однаковим кодом.
```suggestion
Обробник не буде видалено, тому що у `removeEventListener` було передано не ту саму функцію, а іншу, з однаковим кодом.
```

2022-01-31 15:31 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Метод `addEventListener` дозволяє додавати кілька обробників на одну подію одного елемента, наприклад:
```suggestion
Метод `addEventListener` дозволяє додавати декілька обробників на одну подію одного елемента, наприклад:
```

2022-01-31 15:32 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +````warn header="Обробники деяких подій можна присвоїти лише через `addEventListener`"
```suggestion
````warn header="Обробники деяких подій можна призначити лише через `addEventListener`"
```

2022-01-31 15:32 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Наприклад, така подія `DOMContentLoaded`, яке спрацьовує, коли завершено завантаження та побудова DOM документа.
```suggestion
Наприклад, така подія `DOMContentLoaded`, яке спрацьовує, коли завершено завантаження та побудову DOM документа.
```

2022-01-31 15:37 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Ми також можемо використовувати клас для цього:
```suggestion
Ми також можемо використати клас для цього:
```

2022-01-31 15:39 UTC, stas-dolgachov commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Останній спосіб найбільш гнучкий, проте потрібно писати найбільше коду. Є кілька типів подій, які працюють лише через нього, наприклад `transitionend` та `DOMContentLoaded`. Також `addEventListener`
```suggestion
Останній спосіб найбільш гнучкий, проте потрібно писати быльше коду. Є кілька типів подій, які працюють лише через нього, наприклад `transitionend` та `DOMContentLoaded`. Також `addEventListener` підтримує об’єкти-обробники подій. В цьому випадку викликається метод об’єкту `handleEvent`.
```

2022-02-07 15:09 UTC, Regnised commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Останній спосіб найбільш гнучкий, проте потрібно писати найбільше коду. Є кілька типів подій, які працюють лише через нього, наприклад `transitionend` та `DOMContentLoaded`. Також `addEventListener`
Помилка в слові _"быльше"_

2022-02-07 15:10 UTC, Regnised commented
Змерджив виправлення, але є дві помилки. Як тільки підредагуєш запропоновані зміни

2022-02-19 19:40 UTC, Regnised commented
/done

2022-02-20 14:03 UTC, merged