Fetch: Download progress
javascript-tutorial/uk.javascript.info pull request #294
Opened 2022-01-25 21:51 UTC by Nordtonito

2022-01-26 20:49 UTC, stas-dolgachov requested changes
Дякую за чудовий переклад! Подивіться, будь ласка, мої коментарі

2022-01-26 20:49 UTC, stas-dolgachov commented on 5-network/03-fetch-progress/article.md
> +- **`done`** -- `true`, коли зчитування завершено, інакше `false`.
```suggestion
- **`done`** -- `true`, коли зчитування завершено, інакше -- `false`.
```

2022-01-26 20:49 UTC, stas-dolgachov commented on 5-network/03-fetch-progress/article.md
> +Streams API також описує асинхронну ітерацію над `ReadableStream` з циклом `for await..of`, але він ще не широко підтримується (дивись [задачі для браузерів](https://github.com/whatwg/streams/issues/
```suggestion
Streams API також описує асинхронну ітерацію над `ReadableStream` з циклом `for await..of`, але він ще не широко підтримується (дивись [баги браузерів](https://github.com/whatwg/streams/issues/778#issuecomment-461341033)), тому ми використовуємо цикл `while`.
```

2022-01-26 20:49 UTC, stas-dolgachov commented on 5-network/03-fetch-progress/article.md
> +   Зауважте, що ми не можемо використовувати обидва ці методи для зчитування однієї відповіді: щоб отримати результат, скористайтеся зчитувачем `response.json()` або методом `response.body`.
```suggestion
   Зауважте, що ми не можемо використовувати обидва ці методи для зчитування однієї відповіді: щоб отримати результат, скористайтеся зчитувачем `response.json()` або методом `response.body()`.
```

2022-01-26 20:49 UTC, stas-dolgachov commented on 5-network/03-fetch-progress/article.md
> +    Що робити, якщо нам потрібен результат у бінарному вигляді замість рядка? Це ще простіше. Замініть кроки 4 і 5 одним рядком, який створює `Blob` з усіх фрагментів:
Здається, що так краще. Як вважаєшь?
```suggestion
    Що робити, якщо нам потрібен результат у бінарному вигляді замість рядка? Це ще простіше. Замініть кроки 4 і 5 рядком, який створює `Blob` з усіх фрагментів:
```

2022-01-27 11:36 UTC, Nordtonito commented
/done

2022-01-27 11:37 UTC, Nordtonito commented
@stas-dolgachov дякую за оперативну перевірку!

2022-01-28 21:28 UTC, merged