Styles and classes
javascript-tutorial/uk.javascript.info pull request #296
Opened 2022-01-27 09:55 UTC by AdriandeCita

2022-01-27 09:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=296) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=296) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=296) it.</sub>

2022-01-29 23:01 UTC, MykolaSopiha requested changes
Дякую за переклад!

Будь ласка, зверни увагу, що в оригіналі в якості тире використовуються два знаки `--` (особливість Markdown). Ці ж символи треба використовувати і в перекладі. І ще aпостроф потрібно писати знаком `’`, а не одинарною лапкою `'`.

2022-01-29 23:29 UTC, merged

2022-01-30 09:31 UTC, AdriandeCita commented
Ок, прийнято. Ніколи не чув, щоб маркдаун не міг сприймати нормальні тире, але так, без проблем :slightly_smiling_face:

2022-06-28 12:30 UTC, stas-dolgachov commented
@all-contributors please add @stas-dolgachov  for translation