Modifying the document
javascript-tutorial/uk.javascript.info pull request #299
Opened 2022-01-27 23:04 UTC by malechaneit

Перекладено все, включаючи завдання та текст для svg.  Але новий файл before-prepend-append-after.svg не змогла згенерувати (помилки в консолі)

2022-01-27 23:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=299) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=299) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Vita Chukhno<br/>:x: malechaneit<br/><hr/>**Vita Chukhno** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=299) it.</sub>

2022-01-28 21:47 UTC, stas-dolgachov commented
@malechaneit дякуємо за переклад! Щоб ми змогли його прийняти, будь ласка, підпишіть Contributor License Agreement. Там є повідомлення від бота:
```
Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our Contributor License Agreement before we can accept your contribution.
0 out of 2 committers have signed the CLA.
```

2022-01-30 16:34 UTC, MykolaSopiha requested changes

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  */!*
```suggestion
  document.body.append(div);
*!*
  setTimeout(() => div.remove(), 1000);
*/!*
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +Зверніть увагу: якщо ми хочемо _перемістити_ елемент на інше місце в документі - тоді немає потреби його видаляти.
```suggestion
Зверніть увагу: якщо ми хочемо _перемістити_ елемент на інше місце в документі -- тоді немає потреби його видаляти.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +Можна створити функцію та помістити код в неї. Але є ще один спосіб - _клонувати_ існуючий `div` та змінити текст всередині(якщо потрібно).
```suggestion
Можна створити функцію та помістити код в неї. Але є ще один спосіб -- _клонувати_ існуючий `div` та змінити текст всередині(якщо потрібно).
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  }
```suggestion
.alert {
  padding: 15px;
  border: 1px solid #d6e9c6;
  border-radius: 4px;
  color: #3c763d;
  background-color: #dff0d8;
}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +    div2.querySelector('strong').innerHTML = 'Bye there!'; // змінити клона
```suggestion
*!*
  let div2 = div.cloneNode(true); // клонувати елемент
  div2.querySelector('strong').innerHTML = 'Bye there!'; // змінити клона
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  */!*
```suggestion
  div.after(div2); // вставити клонований елемент після існуючого `div`
*/!*
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +`document.write`.
```suggestion
Є ще один дуже застарілий метод щоб додати вміст на веб-сторінку: `document.write`.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +    let result = [];
```suggestion
function getListContent() {
  let result = [];
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +    }
```suggestion
  for(let i=1; i<=3; i++) {
    let li = document.createElement('li');
    li.append(i);
    result.push(li);
  }
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  }
```suggestion
  return result;
}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  */!*
```suggestion
*!*
ul.append(...getListContent()); // append + оператор "..." = друзі!
*/!*
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +За допомою JavaScript ми можемо створити повноцінну веб-сторінку та записати її в документ.
```suggestion
Виклик `document.write(html)` записує `html` на сторінку «прямо тут і зараз». Рядок `html` може бути згенерований динамічно, тож метод дещо гнучкий. За допомою JavaScript ми можемо створити повноцінну веб-сторінку та записати її в документ.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
> +Також важливо встановити новий інтервал у `clockStart()` лише тоді, коли годинник не працює. Інакше натискання кнопки «Пуск» кілька разів встановить кілька одночасних інтервалів. Ще гірше – ми запам'
```suggestion
Також важливо встановити новий інтервал у `clockStart()` лише тоді, коли годинник не працює. Інакше натискання кнопки «Пуск» кілька разів встановить кілька одночасних інтервалів. Ще гірше -- ми запам’ятаємо лише `timerID` останнього інтервалу, втративши посилання на всі інші. В такому разі ми б ніколи більше не змогли зупинити годинник! Зауважте,  в рядку `(**)` нам потрібно очистити `timerID`, коли годинник зупинено, щоб його можна було знову увімкнуи, запустивши `clockStart()`.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/12-sort-table/solution.md
> +2. Потім відсортувати їх порівнюючи за вмістом першого `<td>` (поле «Ім'я»).
```suggestion
2. Потім відсортувати їх порівнюючи за вмістом першого `<td>` (поле «Ім’я»).
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/12-sort-table/solution.view/index.html
> +    <th>Ім'я</th><th>Прізвище</th><th>Вік</th>
```suggestion
    <th>Ім’я</th><th>Прізвище</th><th>Вік</th>
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/12-sort-table/source.view/index.html
> +    <th>Ім'я</th><th>Прізвище</th><th>Вік</th>
```suggestion
    <th>Ім’я</th><th>Прізвище</th><th>Вік</th>
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/12-sort-table/task.md
> +    <th>Ім'я</th><th>Прізвище</th><th>Вік</th>
```suggestion
    <th>Ім’я</th><th>Прізвище</th><th>Вік</th>
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/4-clear-elem/solution.md
> +    elem.childNodes[i].remove();
```suggestion
  for (let i=0; i < elem.childNodes.length; i++) {
  elem.childNodes[i].remove();
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/6-create-list/solution.view/index.html
> +      let data = prompt('Введіть текст для пункту списку', '');
```suggestion
      let data = prompt("Введіть текст для пункту списку", "");
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/build-tree-dom.view/index.html
> +        лосось: {},
```suggestion
        лосось: {}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/build-tree-dom.view/index.html
> +          дуб: {},
```suggestion
          дуб: {}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/build-tree-dom.view/index.html
> +      },
```suggestion
          магнолія: {}
        }
      }
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/innerhtml.view/index.html
> +        лосось: {},
```suggestion
        лосось: {}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/innerhtml.view/index.html
> +          дуб: {},
```suggestion
          дуб: {}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/innerhtml.view/index.html
> +      },
```suggestion
          магнолія: {}
        }
      }
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/solution.md
> +Найпростіший спосіб обійти об'єкт - скористатися рекурсією.
```suggestion
Найпростіший спосіб обійти об’єкт -- скористатися рекурсією.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
> +      дуб: {},
```suggestion
      дуб: {}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
> +  },
```suggestion
      магнолія: {}
    }
  }
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/9-calendar-table/solution.md
> +2. Створіть об'єкт дати `d = new Date(year, month-1)`. Це перший день місяця `month` (беручи до уваги, що місяці в JavaScript починаються з `0`, а не з `1`).
```suggestion
2. Створіть об’єкт дати `d = new Date(year, month-1)`. Це перший день місяця `month` (беручи до уваги, що місяці в JavaScript починаються з `0`, а не з `1`).
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +Маніпуляціїї з DOM(об'єктна модель документа) це ключ до створення «живих» сторінок.
```suggestion
Маніпуляціїї з DOM(об’єктна модель документа) це ключ до створення «живих» сторінок.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  }
```suggestion
.alert {
  padding: 15px;
  border: 1px solid #d6e9c6;
  border-radius: 4px;
  color: #3c763d;
  background-color: #dff0d8;
}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +div.className = 'alert';
```suggestion
div.className = "alert";
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  }
```suggestion
.alert {
  padding: 15px;
  border: 1px solid #d6e9c6;
  border-radius: 4px;
  color: #3c763d;
  background-color: #dff0d8;
}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +    div.innerHTML = "<strong>Всім привіт!</strong> Ви прочитали важливе повідомлення.";
```suggestion
  let div = document.createElement('div');
  div.className = "alert";
  div.innerHTML = "<strong>Всім привіт!</strong> Ви прочитали важливе повідомлення.";
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  */!*
```suggestion
*!*
  document.body.append(div);
*/!*
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +Пам'ятайте, що текст вставляється «як текст», а не «як HTML», з відповідними замінами таких символів як `<`, `>`.
```suggestion
Пам’ятайте, що текст вставляється «як текст», а не «як HTML», з відповідними замінами таких символів як `<`, `>`.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +    let fragment = new DocumentFragment();
```suggestion
function getListContent() {
  let fragment = new DocumentFragment();
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +    }
```suggestion
  for(let i=1; i<=3; i++) {
    let li = document.createElement('li');
    li.append(i);
    fragment.append(li);
  }
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  }
```suggestion
  return fragment;
}
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  */!*
```suggestion
*!*
ul.append(getListContent()); // (*)
*/!*
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +Метод прийшов з тих часів коли не було ані DOM(об'єктна модель документу), ані стандартів... Справді давні часи. Метод досі живий, тому що є скрипти, в яких він використовується.
```suggestion
Метод прийшов з тих часів коли не було ані DOM(об’єктна модель документу), ані стандартів... Справді давні часи. Метод досі живий, тому що є скрипти, в яких він використовується.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/9-calendar-table/solution.view/index.html
> +        if (getDay(d) % 7 == 6) { // НД, останній день тижня - з нового рядка
```suggestion
        if (getDay(d) % 7 == 6) { // НД, останній день тижня -- з нового рядка
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +- `node.replaceWith(...вузли або рядки)` –- замінює `node` заданими вузлами або рядками.
```suggestion
- `node.before(...вузли або рядки)` -- вставляє вузли або рядки _попереду_ `node`,
- `node.after(...вузли або рядки)` -- вставляє вузли або рядки _після_ `node`,
- `node.replaceWith(...вузли або рядки)` -- замінює `node` заданими вузлами або рядками.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +Наведені методи існують для того щоб синтаксис залишався «однорідним». На практиці ж, у більшості випадків використовується `insertAdjacentHTML`. Тому що для вставки елементів та тексту є методи `app
```suggestion
Наведені методи існують для того щоб синтаксис залишався «однорідним». На практиці ж, у більшості випадків використовується `insertAdjacentHTML`. Тому що для вставки елементів та тексту є методи `append/prepend/before/after` -- вони коротші для написання і так само вміють вставляти вузли чи фрагменти тексту.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +Тому якщо нам потрібно динамічно додати в HTML велику кількість тексту, і ми на стадії завантаження сторінки, і швидкість завантаження має значення - цей метод може допомогти. Але на практиці всі ці
```suggestion
Тому якщо нам потрібно динамічно додати в HTML велику кількість тексту, і ми на стадії завантаження сторінки, і швидкість завантаження має значення -- цей метод може допомогти. Але на практиці всі ці вимоги рідко поєднуються. І зазвичай цей метод зустрічається в скриптах лише тому, що вони старі.
```

2022-01-30 16:34 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +  - `node.remove()` –- видаляє `node`.
```suggestion
  - `node.before(...nodes or strings)` -- вставляє прямо перед `node`,
  - `node.after(...nodes or strings)` -- вставляє відразу після `node`,
  - `node.replaceWith(...nodes or strings)` -- замінює `node`.
  - `node.remove()` -- видаляє `node`.
```

2022-01-30 23:00 UTC, MykolaSopiha requested changes

2022-01-30 23:00 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
> +<hr />
```suggestion
<hr>
```

2022-01-30 23:00 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
```suggestion
- Методи для створення нових вузлів:
```

2022-01-30 23:02 UTC, MykolaSopiha requested changes

2022-01-30 23:02 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
```suggestion
```

2022-01-30 23:09 UTC, MykolaSopiha requested changes

2022-01-30 23:09 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
```suggestion
```

2022-01-30 23:09 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
```suggestion
```

2022-01-30 23:09 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
```suggestion
```

2022-01-30 23:12 UTC, MykolaSopiha requested changes

2022-01-30 23:12 UTC, MykolaSopiha commented on 2-ui/1-document/07-modifying-document/article.md
```suggestion
```

2022-01-31 09:08 UTC, malechaneit commented
> @malechaneit дякуємо за переклад! Щоб ми змогли його прийняти, будь ласка, підпишіть Contributor License Agreement. Там є повідомлення від бота:
> 
> ```
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our Contributor License Agreement before we can accept your contribution.
> 0 out of 2 committers have signed the CLA.
> ```

Підписала від імені @malechaneit, а от як це зробити від  Vita Chukhno не розумію.

2022-01-31 12:17 UTC, stas-dolgachov commented
@malechaneit судячи з всього, вам потрібно додати email, який ви використовували для цього комміту (Vita Chukhno) до свого аккаунту в ГітХаб.

2022-01-31 19:27 UTC, malechaneit commented
> @malechaneit судячи з всього, вам потрібно додати email, який ви використовували для цього комміту (Vita Chukhno) до свого аккаунту в ГітХаб.

Так, вже зробила. Але попередні коміти так і залишаться без мейлу, якщо не відредагувати інформацію про автора в конкретному коміті. Без підпису Vita Chukhno мердж буде неможливий?

2022-02-02 18:15 UTC, malechaneit commented
Виправила автора першого коміту, тепер CLA підписаний

2022-02-07 11:44 UTC, stas-dolgachov commented
@MykolaSopiha підкажи, чи потріьно тут ще щось ревьювати? Чи ми можему мерджати? 
Я можу подивитися частину, що залишилася

2022-02-07 16:31 UTC, MykolaSopiha commented
@stas-dolgachov Давай я перегляну ще раз про всяк випадок. Я вже давненько дивився останній раз, тому точно не пам’ятаю що з цим PR.

2022-02-08 10:15 UTC, MykolaSopiha commented
@stas-dolgachov соррі, вчора не було часу подивитися, сьогодні ввечері подивлюсь

2022-02-14 00:01 UTC, MykolaSopiha requested changes

2022-02-14 03:02 UTC, MykolaSopiha commented on 2-ui/2-events/04-default-browser-action/article.md
> +Крім того, якщо ми розглянемо приклад із `<a>`, то зверніть увагу: браузер дозволяє нам відкривати такі посилання в новому вікні (клікаючи їх правою кнопкою миші або іншими способами). І людям таке п
```suggestion
Також якщо ми розглянемо приклад із `<a>`, то зверніть увагу: браузер дозволяє нам відкривати такі посилання в новому вікні (клікаючи на них правою кнопкою миші або іншими способами). І людям таке подобається. Але якщо ми робимо кнопку, яка веде себе як посилання за допомогою JavaScript, і навіть виглядає як посилання за допомогою CSS, тоді `<a>`-специфічні функції браузера все одно не працюватимуть для неї.
```

2022-02-16 23:07 UTC, MykolaSopiha approved these changes
Дякую за переклад!

2022-02-17 00:14 UTC, MykolaSopiha approved these changes

2022-02-17 00:14 UTC, MykolaSopiha commented on 1-js/02-first-steps/02-structure/article.md
> +Дивний вигляд, чи не так? У цьому випадку таке об’єднання неправильне. Щоби код правильно працював, нам потрібно поставити крапку з комою після `alert`.
```suggestion
Виглядає дивно, чи не так? У цьому випадку таке об’єднання неправильне. Щоби код правильно працював, нам потрібно поставити крапку з комою після `alert`.
```

2022-02-17 00:51 UTC, merged