Focus/blur. Translated article and tasks
javascript-tutorial/uk.javascript.info pull request #314
Opened 2022-02-12 06:03 UTC by malechaneit

2022-02-20 15:11 UTC, stas-dolgachov requested changes
Дякую, за чудовий переклад! Це просто клас :) 
Подивіться, будь ласка, на мої коментарі. Якщо, ви незгодні з чимось, напишіть мені ;)

2022-02-20 15:11 UTC, stas-dolgachov commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +З іншого боку, елементи призначені для форматуваня, такі як `<div>`, `<span>`, `<table>` -- за замовчуванням не фокусуються. Метод `elem.focus()` не працює з ними, а події `focus/blur` ніколи не викл
```suggestion
З іншого боку, елементи призначені для форматуваня, такі як `<div>`, `<span>`, `<table>` -- за замовчуванням не фокусуються. Метод `elem.focus()` не працює з ними, а події `focus/blur` ніколи не генеруються.
```

2022-02-20 15:11 UTC, stas-dolgachov commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +Якщо елемент має `tabindex`, то на ньому можна сфокусуватися. Значенням атрибуту є порядковий номер елементу, коли для переходу між елементами використовується клавіша `key:Tab` (або аналогічна).
```suggestion
Якщо елемент має атрибут `tabindex`, то на ньому можна фокусуватися. Значенням атрибуту є порядковий номер елементу, коли для переходу між елементами використовується клавіша `key:Tab` (або аналогічна).
```

2022-02-20 15:11 UTC, stas-dolgachov commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +Клікніть на першому елементі та натисніть Tab. Продовжуйте слідкувати за порядком. Зауважте, що натикаючи Tab багато разів підряд можна вийти за межі iframe з прикладом.
```suggestion
Клікніть на першому елементі та натисніть Tab. Продовжуйте слідкувати за порядком. Зауважте, що натискаючи Tab багато разів підряд можна вийти за межі iframe з прикладом.
```

2022-02-20 15:11 UTC, stas-dolgachov commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +Порядок буде таким: `1 - 2 - 0`. Зазвичай, `<li>` не підтримує фокусування, але `tabindex` вмикає його, разом з подіями та стилізацією псевдоклассу `:focus`.
```suggestion
Порядок буде таким: `1 - 2 - 0`. Зазвичай, `<li>` не підтримує фокусування, але `tabindex` вмикає його, разом із подіями та стилізацією псевдокласу `:focus`.
```

2022-02-20 15:11 UTC, stas-dolgachov commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +Ми можемо додати `tabindex` з JavaScript за допомогою властивості `elem.tabIndex`. Це має той самий ефект.
```suggestion
Ми можемо додати `tabindex` з JavaScript за допомогою властивості `elem.tabIndex`. Це має такий самий ефект.
```

2022-02-20 15:11 UTC, stas-dolgachov commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +- Більшість елементі не підтримують фокусування за замовчуванням. Використовуйте `tabindex` щоб на елементі можна було встановити фокус.
```suggestion
- Більшість елементів не підтримує фокусування за замовчуванням. Використовуйте `tabindex` щоб на елементі можна було встановити фокус.
```

2022-03-01 15:23 UTC, malechaneit commented on 2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
> +- Одночасно можна редагувати лише одну клітину. Поки `<td>` в «режимі редагування», кліки на інших клітинах ігноруються.
Будь-ласка, скиньте посилання на домовленість з приводу розділових знаків при перекладі. В попередньому моєму перекладі всі "" були виправлені на «». Я не проти, але потрібно домовитися

2022-03-01 15:47 UTC, malechaneit commented
/done

2022-03-13 22:26 UTC, stas-dolgachov requested changes

2022-03-13 22:26 UTC, stas-dolgachov commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +    Зазвичай цей прийом використовують, щоб на елементі можна було сфокусуватися не змінюючи стандартний порядок перемикання. Щоб елемент став частиною форми на рівні з `<input>`.
Тут все ще є різниця у номерах рядків. У перекладі це 128, в оригіналі - 129

2022-03-13 22:27 UTC, stas-dolgachov commented
@malechaneit дякую, за виправлення! Лишився малесенький коментар :)

2022-03-25 17:50 UTC, malechaneit commented
/done

2022-03-26 19:32 UTC, stas-dolgachov commented
Дякую за супер переклад! :)

2022-03-26 19:33 UTC, merged