Drag'n'Drop with mouse events
javascript-tutorial/uk.javascript.info pull request #322
Opened 2022-02-23 13:09 UTC by AntonBurchak

2022-02-23 13:11 UTC, AntonBurchak commented
@tarasyyyk Можеш будь-ласка подивитись?)

2022-03-13 22:23 UTC, stas-dolgachov commented
@AntonBurchak привіт, для комітів у цьому пулл реквесті ви використала два різні аккаунти:
✅ AntonBurchak
❌ Anton_Burchak
Для того, щоб ми могли прийняти пулл реквест, потрібно додати другого користувача до вашого GitHub аккаунту

2022-03-21 10:08 UTC, stas-dolgachov requested changes
Дякую за чудовий переклад! Будя ласка, подивіться на мої коментарі. 
Звертаю вашу увагу, що я ще не закінчиві переверку, завершу сьогодні ;)

2022-03-21 10:08 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.js
> +    // спочатку обчислюємо гіпотетичний новий нижній край вікна
Додано рядок, цього не можна робити

2022-03-21 10:08 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.js
> +      // скролл документа на 10px вниз має проблему -
```suggestion
      // прокрутка документа на 10px вниз має проблему --
```

2022-03-21 10:08 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.js
> +      // обмежуємо нове значення Y максимально можливим виходячи з розміру документа:
```suggestion
      // обмежуємо нове значення Y максимально можливим, виходячи з розміру документа:
```

2022-03-21 10:08 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.js
> +    // перевіряємо, чи не переходять нові координати за верхній край вікна (по схожому алгоритму)
```suggestion
    // перевіряємо, чи не переходять нові координати за верхній край вікна (за схожим алгоритмом)
```

2022-03-21 10:08 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.js
> +      // швидке переміщення миші може помістити курсор за межі документа вгору
```suggestion
      // швидке переміщення миші може помістити курсор за межі документа зверху
```

2022-03-21 10:08 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/index.html
> +  <h2>Розставте супергероїв по полю.</h2>
Будь ласка, змініть цей файл, відповідно до моїх коменьтарів вище

2022-03-21 10:08 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
> +  <h2>Розставте супергероїв по полю.</h2>
```suggestion
  <h2>Розставте супергероїв полем.</h2>
```

2022-03-21 10:08 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
> +- Якщо елементи підносять до верхньої/нижньої межі вікна - вікно повинне прокручуватися вгору/вниз, щоб дозволити подальше перетягування.
```suggestion
- Якщо елементи підносять до верхньої/нижньої межі вікна -- вікно повинне прокручуватися вгору/вниз, щоб дозволити подальше перетягування.
```

2022-03-21 12:17 UTC, stas-dolgachov requested changes

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Ось чому ми повинні відстежувати `mousemove` на усьому `document`, щоб упіймати його.
```suggestion
Ось чому ми повинні відстежувати `mousemove` на усьому `document`, щоб упіймати його у будь-якому разі.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Непогано, але є побічний ефект. Щоб ініціювати перенесення, ми можемо натиснути у будь-якому місці кулі. Але якщо "узяти" його з краю, то куля несподівано "підстрибне", щоб стати по центру під курсор
```suggestion
Непогано, але є побічний ефект. Щоб ініціювати перенесення, ми можемо натиснути у будь-якому місці кулі. Але якщо "узяти" його з краю, то м’яч несподівано "підстрибне", щоб стати по центру під курсором миші.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Наприклад, якщо ми "схопились" за край кульки, то курсор повинен залишатися над краєм під час перенесення.
```suggestion
Наприклад, якщо ми "схопили" за край м’яча, то курсор повинен залишатися над краєм під час перенесення.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Відмінність особливо помітна, якщо захопити м’яч за правий нижній кут. У попередньому прикладі м’ячик "стрибне" серединою під курсор, а в цьому - плавно переноситиметься з поточної позиції.
```suggestion
Відмінність особливо помітна, якщо захопити м’яч за правий нижній кут. У попередньому прикладі м’ячик "стрибне" серединою під курсор, а в цьому -- плавно переноситиметься з поточної позиції.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +У попередніх прикладах м’яч можна було кинути просто де завгодно в межах вікна. У реальності ми зазвичай беремо один елемент і перетягуємо в іншій. Наприклад, "файл" в "папку" або щось ще.
```suggestion
У попередніх прикладах м’яч можна було кинути просто де завгодно в межах вікна. На практиці ми зазвичай беремо один елемент і перетягуємо в іншій. Наприклад, "файл" в "папку" або щось ще.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +- де елемент був залишений у кінці Drag'n'Drop - для виконання відповідної дії,
```suggestion
- де елемент був залишений у кінці Drag'n'Drop -- для виконання відповідної дії,
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Рішення досить цікаве і трохи навіть хитре, давайте розглянемо його.
```suggestion
Рішення досить цікаве і трохи нестандартне, давайте його розглянемо.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Якою може бути перша думка? Можливо, встановити обробники подій `mouseover/mouseup` на елемент - потенційну ціль перенесення?
```suggestion
Якою може бути перша думка? Можливо, встановити обробники подій `mouseover/mouseup` на елемент -- потенційну ціль перенесення?
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Але це не працює.
```suggestion
Але це не спрацює.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Те ж саме з перетягуючим елементом. м’яч завжди знаходиться поверх інших елементів, тому події спрацьовують на ньому. Які б обробники ми не встановили на нижні елементи, вони не будуть виконані.
```suggestion
Те ж саме з перетягуючим елементом. М’яч завжди знаходиться поверх інших елементів, тому події спрацьовують на ньому. Які б обробники ми не встановили на нижні елементи, вони не будуть виконані.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Ось чому початкова ідея встановити обробники на потенційні цілі перенесення нереалізуема. Обробники не спрацюють.
```suggestion
Ось чому початкова ідея встановити обробники на потенційні цілі перенесення не спрацює на практиці. Обробники не будуть викликатися.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Ми можемо використовувати його, щоб з будь-якого обробника подій миші з’ясувати, над якою ми потенційною ціллю перенесення, ось так:
```suggestion
Ми можемо використати його, щоб з будь-якого обробника подій миші з’ясувати, над якою ми потенційною ціллю перенесення, ось так:
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +// elemBelow - елемент під м’ячем (можлива ціль перенесення)
```suggestion
// elemBelow -- елемент під м’ячем (можлива ціль перенесення)
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Ми можемо використовувати цей код для перевірки того, над яким елементом ми «летимо», в будь-який час. І обробити закінчення перенесення, коли воно станеться.
```suggestion
Ми можемо використовувати цей код для перевірки того, над яким елементом ми "летимо", в будь-який час. І обробити закінчення перенесення, коли воно станеться.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +    //    якщо ми були не над droppable до цієї події (наприклад, над порожнім простором)
Тут э зайві рядки, це змінює структуру документу

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +      // логіка обробки процесу, коли ми "влітаємо" в елемент droppable
```suggestion
      // логіка обробки процесу, коли ми "влітаємо" на елемент droppable
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +2. На початку перетягування -- запам’ятовуємо початкове зміщення покажчика щодо елемента: `shiftX/shiftY` - і зберігаємо його при перетягуванні.
```suggestion
2. На початку перетягування -- запам’ятовуємо початкове зміщення курсору щодо елемента: `shiftX/shiftY` і зберігаємо його при перетягуванні.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +3. Виявляємо потенційні цілі перенесення під покажчиком за допомогою `document.elementFromPoint`.
```suggestion
3. Виявляємо потенційні цілі перенесення під курсором за допомогою `document.elementFromPoint`.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +- Можна підсвічувати елементи, поки курсос «пролітає» над ними.
```suggestion
- Можна підсвічувати елементи, поки курсор "пролітає" над ними.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +- І так далі.
```suggestion
- І так інше.
```

2022-03-21 12:17 UTC, stas-dolgachov commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Існують фреймворки, які будують архітектуру над ним: `DragZone`, `Droppable`, `Draggable` та інші класи. Більшість з них роблять те ж саме, що описано вище, так що розібратися в них не буде проблемою
```suggestion
Існують фреймворки (бібліотеки), які будують архітектуру нвд цим алгоритмом: `DragZone`, `Droppable`, `Draggable` та інші. Більшість з них роблять те ж саме, що описано вище, так що розібратися в них не буде проблемою. Або створити свій власний, як ви бачите, це досить просто зробити, іноді простіше, ніж адаптувати стороннє рішення.
```

2022-03-22 20:26 UTC, AntonBurchak commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> -  // to make it positioned relative to the body
Updated

2022-03-22 20:28 UTC, AntonBurchak commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +    //    якщо ми були не над droppable до цієї події (наприклад, над порожнім простором)
Updated

2022-03-22 20:31 UTC, AntonBurchak commented
@stas-dolgachov Дякую за ретельне ревью. Я вніс корективи до перекладу, будь-ласка перевірте

2022-03-25 18:10 UTC, AntonBurchak commented
/done

2022-03-26 19:40 UTC, stas-dolgachov approved these changes

2022-03-26 19:41 UTC, stas-dolgachov commented
Дякую за чудовий переклад!

2022-03-26 19:41 UTC, merged