URL objects
javascript-tutorial/uk.javascript.info pull request #323
Opened 2022-03-19 20:05 UTC by Purusah

2022-04-04 06:36 UTC, stas-dolgachov reviewed
Дякую, за чудовий переклад! Подивіться, будь ласка, мої коментарі ;) Напишыть мены, якщо будуть якись запитання

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +```smart header="`URL` об'єкт можна передати у методи, що використовуються для мережевих запитів замість рядку"
```suggestion
```smart header="`URL` об’єкт можна передати у методи, що використовуються для мережевих запитів замість рядку"
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +`fetch` чи `XMLHttpRequest` можуть отримувати `URL` об'єкти майже всюди, де можна передати рядок з URL.
```suggestion
`fetch` чи `XMLHttpRequest` можуть використовувати `URL` об’єкти майже всюди, де можна передати рядок з `URL`.
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Зазвичай, `URL` об'єкт можна передати в будь-який метод замість рядку, оскільки більшість методів перетворять об'єкт в рядок, що містить повну URL-адресу.
```suggestion
Зазвичай, `URL` об’єкт можна передати в будь-який метод замість рядку, оскільки більшість методів перетворять об’єкт в рядок, що містить повну URL-адресу.
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Отже, для цього `URL` має властивість: `url.searchParams`, об'єкт типу [URLSearchParams](https://url.spec.whatwg.org/#urlsearchparams).
```suggestion
Отже, для цього `URL` має властивість: `url.searchParams`, об’єкт типу [URLSearchParams](https://url.spec.whatwg.org/#urlsearchparams).
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +- **`append(name, value)`** -- додати параметр з ім'ям `name`,
```suggestion
- **`append(name, value)`** -- додати параметр з іменем `name`,
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +- ...і це об'єкт також можна перебрати, подібно до `Map`.
```suggestion
- ...і це об’єкт також можна перебрати, подібно до `Map`.
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Усі інші символи, що не дозволені стандартом, повинні бути закодовані. Наприклад, не латинські букви та пробіл повинні бути заміненими на їх UTF-8 коди, що починаються з `%`. Пробіл буде закодовано у
```suggestion
Усі інші символи, що не дозволені стандартом, повинні бути закодовані. Наприклад, не латинські букви та пробіли мають бути замінені на їх UTF-8 коди, що починаються з `%`. Пробіл буде закодовано у вигляді `%20` (з історичних причин пробіл дозволено закодувати як `+`).
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Гарна новина полягає в тому, що `URL` об'єкт виконає всі перетворення автоматично. Нам потрібно тільки передати всі параметри, а потім перетворити `URL` в рядок:
```suggestion
Гарна новина полягає в тому, що `URL` об’єкт виконає всі перетворення автоматично. Нам потрібно тільки передати всі параметри, а потім перетворити `URL` в рядок:
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +До появи `URL`, розробники використовували рядки для URL-адрес.
```suggestion
До появи `URL` об’єктів, розробники використовували рядки для URL-адрес.
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Наразі, зручніше використовувати `URL`, але рядки все ще можна використовувати. У більшості випадків, використання рядків потребує менше коду.
```suggestion
Наразі, зручніше використовувати `URL` об’єкти, але рядки все ще можна використовувати. У більшості випадків, використання рядків потребує менше коду.
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +- [encodeURIComponent](mdn:/JavaScript/Reference/Global_Objects/encodeURIComponent) - закодувати частину URL-адреси, наприклад, параметри пошуку, шлях чи геш.
```suggestion
- [encodeURIComponent](mdn:/JavaScript/Reference/Global_Objects/encodeURIComponent) - закодувати частину URL-адреси, наприклад, параметри пошуку, шлях чи хеш.
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Може виникнути природне питання: "Яка різниця між `encodeURIComponent` та `encodeURI`? В якому випадку краще використовувати кожну функцію?"
```suggestion
Може виникнути природне питання: "Яка різниця між `encodeURIComponent` та `encodeURI`? Коли використовувати яку?"
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Це стає легше зрозуміти, якщо подивитися на URL-адресу, що показано розділеною на частини вище.
```suggestion
Це легше зрозуміти, якщо подивитися на URL-адресу, що показано розділеною на частини вище.
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Нам слід використовувати тільки `encodeURIComponent` з параметрами пошуку для правильного вставлення в рядок URL. Для повної безпеки, слід кодувати ім'я та значення параметрів, якщо ми не можемо бути
```suggestion
Нам слід використовувати тільки `encodeURIComponent` з параметрами пошуку для правильного вставлення в рядок URL. Для повної безпеки, слід кодувати ім’я та значення параметрів, якщо ми не можемо бути повністю впевненими, що вони містять тільки дозволені символи.
```

2022-04-04 06:36 UTC, stas-dolgachov commented on 5-network/07-url/article.md
> +Як бачимо, `encodeURI` заміню квадратні дужки `[...]`, що є помилкою, причиною є те, що IPv6 адреси ще не існували в часи створення стандарту RFC2396 (серпень 1998).
```suggestion
Як бачимо, `encodeURI` замінила квадратні дужки `[...]`, що є помилкою, причиною є те, що IPv6 адреси ще не існували в часи створення стандарту RFC2396 (серпень 1998).
```

2022-04-04 06:38 UTC, stas-dolgachov requested changes
Якщо згодні, додавайте мої зміни і завершемо переклад =)

2022-04-04 18:55 UTC, Purusah commented
Дякую за виправлення, все додав

2022-04-04 18:55 UTC, Purusah commented
/done

2022-04-15 13:24 UTC, stas-dolgachov approved these changes

2022-04-15 13:25 UTC, merged

2022-06-28 13:05 UTC, stas-dolgachov commented
@all-contributors please add @Purusah  for translation