Document cookie
javascript-tutorial/uk.javascript.info pull request #324
Opened 2022-03-25 17:26 UTC by malechaneit

2022-04-14 11:38 UTC, stas-dolgachov requested changes
Дякую за пречудовий переклад! Я дійсно вражений! 
Я там багато разів виправляв cookie => cookies, зроблино це лише тому, що в оригіналі так написано. Але ви можете самі вирішити чи приймати ці зміни. Ще раз дякую!

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Це обмеження задля безпеки, воно дозволяє нам зберігати конфіденційні дані в файлах cookie, які будуть достпуними лише на одному сайті.
```suggestion
Це обмеження задля безпеки, воно дозволяє нам зберігати конфіденційні дані в файлах cookie, які будуть доступними лише на одному сайті.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +// якщо задати файл cookie на web-сайті site.com ...
```suggestion
// якщо задати файл cookie на вебсайті site.com ...
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Історично склалося так що, `domain=.site.com`(з крапкою перед `site.com`)   зпрацює так само, надаючи доступ до файлів cookie з піддоменів. Цей застарілий синтаксис варто використовуваи лише якщо пот
```suggestion
Історично склалося так що, `domain=.site.com`(з крапкою перед `site.com`) спрацює так само, надаючи доступ до файлів cookie з піддоменів. Цей застарілий синтаксис варто використовувати лише якщо потрібна підтримка дуже старих браузерів.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +За замовчуванням, якщо файл cookie не має одного з цих параметрів, то файл зникає при закриванні браузера. Такі файли cookie називаються сесійними ("session cookies").
```suggestion
За замовчуванням, якщо файл cookie не має одного з цих параметрів, то файл зникає при закриванні браузера. Такі файли cookies називаються сесійними ("session cookies").
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Щоб файли cookie могли "пережити" закривання браузера, можна встановити значення одного з параметрів `expires` або `max-age`.
```suggestion
Щоб файли cookies могли "пережити" закривання браузера, можна встановити значення одного з параметрів `expires` або `max-age`.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +
Цей рядок потрібно видалити, церез нього змінилась кількість рядків у файлі

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +В разі якщо цей параметр задано, то файл cookie створений на `https://site.com` не буде доступний на тому ж web-сайті з HTTP-протоколом `http://site.com`. Тому якщо файли cookie містять конфіденційні
```suggestion
В разі якщо цей параметр задано, то файл cookie створений на `https://site.com` не буде доступний на тому ж вебсайті з HTTP-протоколом `http://site.com`. Тому якщо файли cookie містять конфіденційні дані, які в жодному разі не мають бути відправлені по незашифрованому HTTP-протоколу, тоді параметр `secure` це правильнйи вибір.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Уявіть, що ви увійшли в свій обліковий запис на сайті `bank.com`. Тобто: у вас є файли cookie з даними аторизації. Ваш браузер відправляє їх web-сайту `bank.com` при кожному запиті для того щоб той р
```suggestion
Уявіть, що ви увійшли в свій обліковий запис на сайті `bank.com`. Тобто: у вас є файли cookie з даними аутентифікації. Ваш браузер відправляє їх вебсайту `bank.com` при кожному запиті для того щоб той розпізнав вас та виконав всі конфіденційні фінансові операції.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Тепер, переглядаючи web-сторінки в іншому вікні, ви випадково потрапили на сайт `evil.com`. Цей сайт містить  код JavaScript, який відправляє форму `<form action="https://bank.com/pay">` на `bank.com
```suggestion
Тепер, переглядаючи вебсторінки в іншому вікні, ви випадково потрапили на сайт `evil.com`. Цей сайт містить код JavaScript, який відправляє форму `<form action="https://bank.com/pay">` на `bank.com` з заповненими полями, які ініціюють транзакцію на рахунок хакера.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Браузер відправляє файл cookie щоразу як ви відвідуєте сайт `bank.com`, навіть якщо форма була відпралена з `evil.com`. Тому банк "впізнає" вас та дійсно виконає платіж.
```suggestion
Браузер відправляє файл cookies щоразу як ви відвідуєте сайт `bank.com`, навіть якщо форма була відпралена з `evil.com`. Тому банк "впізнає" вас та дійсно виконає платіж.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Параметр `samesite` пропонує ще один спосіб захисту від атак, який ( в теорії) не вимагає "токен захисту від xsrf".
```suggestion
Параметр `samesite` пропонує ще один спосіб захисту від атак, який (в теорії) не вимагає "токен захисту від xsrf".
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Захист доволі найдійний. Файли cookie з параметром `samesite` відправлятимуться тільки якщо операції надходять з `bank.com`, наприклад відправка форми з іншої сторінки домену `bank.com`.
```suggestion
Захист доволі надійний. Файли cookie з параметром `samesite` відправлятимуться тільки якщо операції надходять з `bank.com`, наприклад відправка форми з іншої сторінки домену `bank.com`.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Хоча, у цього рішення є дрібний недолік.
```suggestion
Хоча, у цього рішення є маленький недолік.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Цю проблему можна вирішити використанням двох файлів cookie: один для загальної ідентифакації, лише для того щоб сказати: "Привіт, Джон", а інший з параметром `samesite=strict` для операцій з даними.
```suggestion
Цю проблему можна вирішити використанням двох файлів cookie: один для загальної ідентифакації, лише для того щоб сказати: "Привіт, Іван", а інший з параметром `samesite=strict` для операцій з даними. Тоді особа, яка перейшла за посиланням поза межами сайту побачить привітання, проте для того щоб другий файл cookie відправився, платіжні операції повинні бути ініційовані з сайту банку.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Режим `lax`, так само як `strict`, забороняє браузеру відправляти файл cookie коли запит приходить не з сайту, але є одне виключення.
```suggestion
Режим `lax`, так само як `strict`, забороняє браузеру відправляти файл cookies коли запит приходить не з сайту, але є одне виключення.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Тому насправді, все що робить параметр `samesite=lax` -  це дозволяє найбільш поширеним операціям (таким як перехід по URL) передавати файли cookie. Наприклад, відкривання web-сайту за посиланям зі с
```suggestion
Тому насправді, все що робить параметр `samesite=lax` --  це дозволяє найбільш поширеним операціям (таким як перехід по URL) передавати файли cookie. Наприклад, відкривання вебсайту за посиланям зі своїх нотаток, що повністю задовольняє умовам.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Але будь-яка більш складна операція, як то мережевий запит з іншого сайту чи відправка форми, втрачає файли cookie.
```suggestion
Але будь-яка більш складна операція, як то мережевий запит з іншого сайту чи відправка форми, втрачає файли cookies.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Вцілому, `samesite` це чудовий параметр.
```suggestion
В цілому, `samesite` -- це чудовий параметр.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +- `samesite` ігнорується  (не підтримується) старими версіями браузерів, з 2017 року і раніше.
```suggestion
- `samesite` ігнорується  (не підтримується) старими версіями браузерів, до 2017 року і раніше.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Звісно,ми можемо використовувати `samesite` разом з іншими засобами безпеки, такими як "токен захисту від xsrf", щоб додати ше один рівень захисту, а потім в майбутньому, коли старі браузери вимруть,
```suggestion
Звісно, ми можемо використовувати `samesite` разом з іншими засобами безпеки, такими як "токен захисту від xsrf", щоб додати ше один рівень захисту, а потім в майбутньому, коли старі браузери вимруть, ми зможемо відмовитися від токенів.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Web-сервер використовує заголовок `Set-Cookie` щоб задати файли cookie. Також він може встановити параметр `httpOnly`.
```suggestion
Вебсервер використовує заголовок `Set-Cookie` щоб задати файли cookie. Також він може встановити параметр `httpOnly`.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Зазвичай, якщо таке трапляється, і користувач все ж зайшов на web-сторінку с хакерським кодом JavaScript, тоді код виконується та отримує доступ до команди `document.cookie`, яка містить аутентифікац
```suggestion
Зазвичай, якщо таке трапляється, і користувач все ж зайшов на вебсторінку с хакерським кодом JavaScript, тоді код виконується та отримує доступ до команди `document.cookie`, яка містить аутентифікаційну інформацію. Це погано.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Тут наведено невелику підбірку функцій для роботи з файлами cookie, більш зручних аніж ручна модифікація  `document.cookie`.
```suggestion
Тут наведено невелику підбірку функцій для роботи з файлами cookie, більш зручних аніж ручна модифікація  `document.cookie`.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +```warn header="Операція оновлення або видалення повинні використовувати ті самі адресу та домен."
```suggestion
```warn header="Операції оновлення або видалення повинні використовувати ті самі адресу та домен."
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +## Додаток: Сторонні файли cookie
```suggestion
## Додаток: Сторонні файли cookies
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +Зауважте, що йдеться лише про відстеження/ідентифікацію/авторизацію файлів cookie.
```suggestion
Зауважте, що йдеться лише про відстеження/ідентифікацію/авторизацію файлів cookies.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +1. Якщо web-сайт хоче встановити відслідковуючі файли cookie лише для аутентифікованих користувачів.
```suggestion
1. Якщо вебсайт хоче встановити відслідковуючі файли cookie лише для аутентифікованих користувачів.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +     Для цього в реєстраційній формі має бути прапорець на кшталт «прийняти політику конфіденційності» (яка описує, як використовуються файли cookie), користувач повинен відмітити його, лише тоді web
```suggestion
     Для цього в реєстраційній формі має бути прапорець на кшталт "прийняти політику конфіденційності" (яка описує, як використовуються файли cookie), користувач повинен відмітити його, лише тоді вебсайт може встановлювати файли cookie для авторизації.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +2. Якщо web-сайт хоче встановити відстежуючі файли cookie для всіх.
```suggestion
2. Якщо вебсайт хоче встановити відстежуючі файли cookies для всіх.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +     Щоб зробити це законно, web-сайт показує спливаюче модальне вікно для нових користувачів і вимагає від них погодитися на файли cookie. Тоді web-сайт може встановлювати їх і дозволити людям бачит
```suggestion
     Щоб зробити це законно, вебсайт показує спливаюче модальне вікно для нових користувачів і вимагає від них погодитися на файли cookie. Тоді web-сайт може встановлювати їх і дозволити людям бачити контент. Але це може турбувати нових відвідувачів. Ніхто не любить бачити такі спливаючі модальні вікна, які вимагають взаємодії, замість перегляду контенту. Але GDPR вимагає чіткої угоди.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +`document.cookie` забезпечує доступ до файлів cookie
```suggestion
`document.cookie` забезпечує доступ до файлів cookies
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +- операції запису змінюють лише вказані файли cookie.
```suggestion
- операції запису змінюють лише вказані файли cookies.
```

2022-04-14 11:38 UTC, stas-dolgachov commented on 6-data-storage/01-cookie/article.md
> +У Європі існує законодавство під назвою GDPR, яке встановлює набір правил для веб-сайтів щодо поваги до конфіденційності користувачів. Одне з цих правил — вимагати від користувача явного дозволу на в
```suggestion
У Європі існує законодавство під назвою GDPR, яке встановлює набір правил для вебсайтів щодо поваги до конфіденційності користувачів. Одне з цих правил — вимагати від користувача явного дозволу на відстеження файлів cookie.
```

2022-04-14 14:24 UTC, malechaneit commented
> Дякую за пречудовий переклад! Я дійсно вражений! Я там багато разів виправляв cookie => cookies, зроблино це лише тому, що в оригіналі так написано. Але ви можете самі вирішити чи приймати ці зміни. Ще раз дякую!

Мені також було складно визначитися з підходящим перекладом слова cookies. Але я вирішила, що оскільки в українській версії з'являється слово "файли", то воно може взяти на себе множину власне слова cookie. Тобто там де в оригіналі cookie ==> файл cookie, а якщо cookieS ==> файлИ cookie. Як ви вважаєте чи є в цьому сенс?

2022-04-15 13:20 UTC, stas-dolgachov commented
@malechaneit насправді, я просто хотів залиши cookies там де в оригіналі бeло cookies. 
Це лише задля консістенсності з оригінальним текстом. 
При цьому поряд з cookies, з моєї точки зору, можна використовувати як "файл" так і "файли". 
Переклад з використанням "файл" мені дуже сопдобався, ви молодець!

2022-04-29 06:58 UTC, merged