LocalStorage, sessionStorage
javascript-tutorial/uk.javascript.info pull request #325
Opened 2022-03-27 19:18 UTC by AntonBurchak

2022-04-14 09:47 UTC, stas-dolgachov requested changes
Дякую, за переклад, подивіться, будь ласка на мої коментарі

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +2. Існує подія `storage`, вона запускається, коли ми змінюємо дані. Ця подія не відбувається при зміні даних без виклику `setItem`. Ми побачимо це пізніше в цьому розділі.
```suggestion
2. Існує подія `storage`, вона запускається, коли ми змінюємо дані. Ця подія не відбувається при зміні даних без виклику `setItem`. Ми поговоримо про це пізніше в цьому розділі.
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +## Перебирання ключів
```suggestion
## Перебір ключів
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Як ми бачили, методи забезпечують функцію «отримати/встановити/видалити за ключем». Але як отримати всі збережені значення чи ключі?
```suggestion
Як ми бачили, методи забезпечують функцію "отримати/записати/видалити за ключем". Але як отримати всі збережені значення чи ключі?
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Один із способів - маніпулювати ними як з масивом:
```suggestion
Один із способів -- працювати з ними як з масивом:
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Інший спосіб — використовувати цикл `for key in localStorage`, так само, як ми робимо зі звичайними об’єктами.
```suggestion
Інший спосіб -- використати цикл `for key in localStorage`, так само, як для звичайних об’єктів.
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Він перебирає ключі, але також виводить кілька вбудованих полів, які нам не потрібні:
```suggestion
Він перебирає ключі, але також виводить кілька вбудованих властивостей, які нам не потрібні:
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +// погана спроба
```suggestion
// невдала спроба
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +  alert(key); // показує getItem, setItem та інші вбудовані елементи
```suggestion
  alert(key); // показує getItem, setItem та інші вбудовані властивості
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +...Або просто отримати «власні» ключі за допомогою `Object.keys`, а потім переглянути їх, якщо потрібно:
```suggestion
...Або просто отримати "власні" ключі за допомогою `Object.keys`, а потім перебрати їх, якщо потрібно:
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Якби був будь-який інший тип, наприклад число або об’єкт, він автоматично перетворився б на рядок:
```suggestion
Якщо ми спробуємо використати будь-який інший тип, наприклад число або об’єкт, він автоматично перетвориться на рядок:
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Однак ми можемо використовувати `JSON` для зберігання об’єктів:
```suggestion
Однак ми можемо використати `JSON` для зберігання об’єктів:
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +``` js run
```suggestion
```js run
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Також можна об’єднати весь об’єкт сховища в рядки, наприклад, для цілей налагодження:
```suggestion
Також можна перетворити весь об’єкт сховища на JSON рядок, наприклад, підчас налагодження коду:
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +``` js run
```suggestion
```js run
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +``` js run
```suggestion
```js run
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +``` js run
```suggestion
```js run
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Властивості та методи ті самі, але набагато більш обмежені:
```suggestion
Властивості та методи ті самі, але можливості більш обмежені:
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +  - Але він використовується між iframes на одній вкладці (за умови, що вони походять з одного джерела).
```suggestion
  - Але він використовується між iframes на одній вкладці (за умови, що це один сайт).
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +...Тоді оновіть сторінку. Тепер ви все ще можете отримати дані:
```suggestion
...Потім оновіть сторінку. Тепер ви все ще можете отримати дані:
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Це саме тому, що `sessionStorage` прив’язаний не лише до джерела, а й до вкладки браузера. З цієї причини `sessionStorage` використовується не часто.
```suggestion
Це саме тому, що `sessionStorage` прив’язаний не лише до сайту, а й до вкладки браузера. З цієї причини `sessionStorage` використовується не часто.
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +## Подія Storage
```suggestion
## Подія storage
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +- `oldValue` – старе значення (`null`, якщо ключ додано знову).
```suggestion
- `oldValue` – старе значення (`null`, якщо це новий ключ).
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +- `newValue` – нове значення (`null`, якщо ключ видалено).
```suggestion
- `newValue` – нове значення (`null`, якщо дані видалено).
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +  if (event.key != 'зараз') return;
```suggestion
  if (event.key != 'now') return;
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +localStorage.setItem('зараз', ​​Date.now());
```suggestion
localStorage.setItem('now', ​​Date.now());
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Крім того, `event.storageArea` містить об’єкт сховища -- подія однакова для `sessionStorage` та `localStorage`, тому `event.storageArea` посилається на той, який було змінено. Ми навіть можемо захоті
```suggestion
Крім того, `event.storageArea` містить об’єкт сховища -- подія однакова для `sessionStorage` та `localStorage`, тому `event.storageArea` посилається на той, який було змінено. Ми навіть можемо захотіти щось змінити в ньому, "відреагувати" на зміни.
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +**Це дозволяє різним вікнам з одного джерела обмінюватися повідомленнями.**
```suggestion
**Це дозволяє різним вікнам одного сайту обмінюватися повідомленнями.**
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +Сучасні браузери також підтримують [Broadcast channel API](mdn:/api/Broadcast_Channel_API), спеціальний API для міжвіконного зв’язку одного джерела, він більш повнофункціональний, але менш підтримуєт
```suggestion
Сучасні браузери також підтримують [Broadcast channel API](mdn:/api/Broadcast_Channel_API), спеціальний API для міжвіконного зв’язку одного джерела, він більш повнофункціональний, але має меншу підтримку серед браузерів. Існують бібліотеки-поліфіли цього API на основі `localStorage`, що робить його доступним майже скрізь.
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +## Висновки
```suggestion
## Підсумки
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +— Дані не мають "терміну дії", тобто не видаляються.
```suggestion
- Дані не мають терміну зберіганя, тобто не видаляються.
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +- Дані прив’язані до джерела (домен/порт/протокол).
```suggestion
- Дані прив’язані до сайту (домен/порт/протокол).
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +| Спільний для всіх вкладок і вікон з однаковим джерелом | Відображається на вкладці браузера, включаючи iframe з того самого джерела |
```suggestion
| Спільний для всіх вкладок і вікон з однаковим сайтом | Відображається у вкладці браузера, включаючи iframe того самого сайту|
```

2022-04-14 09:47 UTC, stas-dolgachov commented on 6-data-storage/02-localstorage/article.md
> +- Ми маємо доступ до ключів як властивостей об’єкта та можемо з ними маніпулювати, у цьому випадку подія `storage` не ініціюється.
```suggestion
- Ми маємо доступ до ключів як властивостей об’єкта та можемо ними маніпулювати, у цьому випадку подія `storage` не ініціюється.
```

2022-04-27 04:28 UTC, stas-dolgachov commented
@AntonBurchak привіт, можеш подивитися мої коментарі?

2022-04-27 11:59 UTC, AntonBurchak commented
> @AntonBurchak привіт, можеш подивитися мої коментарі?

Так, вибач, сьогодні-завтра подивлюсь та апдейтну ПР) Просто запара із дипломом :(

2022-04-29 06:47 UTC, stas-dolgachov commented
@AntonBurchak  все нормально, я сам їх перевірив ще раз і застосував.

2022-04-29 06:47 UTC, merged