clickjacking
javascript-tutorial/uk.javascript.info pull request #343
Opened 2022-06-07 03:10 UTC by astropsy999

2022-06-28 12:04 UTC, stas-dolgachov requested changes
Дякую, за чудовий переклад! Я подивився деякі статті і залишив кілька коментарів. Подивись їх, будь ласка. 

Але як я бачу у цьому пул реквесті перекладені статті з іншого: #342 
5-network/12-server-sent-events/article.md
6-data-storage/03-indexeddb/article.md

Який з них правильний? Ви не могли закрити #342, якщо він більше не потрібен?

2022-07-12 09:37 UTC, stas-dolgachov commented
#1

2022-07-16 07:18 UTC, astropsy999 reviewed
Ok

2022-07-17 06:27 UTC, astropsy999 reviewed
approved

2022-07-19 10:30 UTC, stas-dolgachov requested changes
Дякую за чудовий переклад, вибачте що я так довго його перевіряв, але тут багатенько перекладено, а я обмежений у часі через роботу і інши проєкти =) 

Подивіться, будь ласка, мої коментарі =)

За можливістю наступного разу робіть переклади кількох статей оркемими пеулл реквестами, це пришвидшить їх перевірку у рази.

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Ми можемо бачити, що під час анімації: коли ми клацаємо по цифрі, вона відразу змінюється на `1` (перший крок), а потім змінюється на початку наступної секунди.
```suggestion
Можна помітити, що під час анімації: коли ми клацаємо по цифрі, вона відразу змінюється на `1` (перший крок), а потім змінюється на початку наступної секунди.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Процес протікає так:
```suggestion
Процес іде так:
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +- `0s` -- `-10%` (перша зміна на початку 1-ї секунди, відразу)
```suggestion
- `0s` -- `-10%` (перша зміна на початку 1-ої секунди, відразу)
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +- `1s` -- `-10%` (перша зміна в кінці 1-ї секунди)
```suggestion
- `1s` -- `-10%` (перша зміна в кінці 1-ої секунди)
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +- `step-start` -- те саме, що `steps(1, start)`. Тобто анімація починається відразу і займає 1 крок. Вона починається й закінчується одразу, ніби не було анімації.
```suggestion
- `step-start` -- те саме, що й `steps(1, start)`. Тобто анімація починається відразу і займає 1 крок. Вона починається й закінчується одразу, ніби не було анімації.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +- `step-end` -- те саме, що `steps(1, end)`: створіть анімацію за один крок у кінці `transition-duration`.
```suggestion
- `step-end` -- те саме, що й `steps(1, end)`: зробіть анімацію за один крок у кінці `transition-duration`.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Вона широко використовується для виконання дії після завершення анімації. Також ми можемо приєднатися до анімації з її допомогою.
```suggestion
Вона широко використовується для виконання дії після завершення анімації. Також ми можемо об’єднувати анімації з її допомогою.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Анімація ініціюється функцією `go`, яка повторно запускається кожного разу, коли закінчується перехід, і повертає напрямок:
```suggestion
Анімація ініціюється функцією `go`, яка повторно запускається кожного разу, коли закінчується перехід, і повертає напрямок:
```
```suggestion
Анімація ініціюється функцією `go`, яка повторно запускається кожного разу, коли закінчується перехід, і змінює напрямок на протилежний:
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Об’єкт події для `transitionend` має кілька конкретних властивостей:
```suggestion
Об’єкт події для `transitionend` має кілька специфічних властивостей:
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +: Властивість, яка завершила анімацію. Може бути корисна коли ми анімуємо кілька властивостей одночасно.
```suggestion
: Ім’я властивості, для якої завершилась анімація. Може бути корисна коли ми анімуємо кілька властивостей одночасно.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +: Час (у секундах), який займала анімація, без `transition-delay`.
```suggestion
: Час (у секундах), який тривала анімація, без `transition-delay`.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +## Ключові кадри
```suggestion
## Keyframes
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Ми можемо об’єднати кілька простих анімацій разом за допомогою правила CSS `@keyframes`.
```suggestion
Ми можемо об’єднати кілька простих анімацій разом за допомогою CSS правила `@keyframes`.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Воно визначає "ім’я" анімації та правила - що, коли і де анімувати. Використовуючи властивість `animation`, ми можемо приєднати анімацію до елемента та вказати додаткові параметри.
```suggestion
Воно визначає "ім’я" анімації та правила -- що, коли і де анімувати. Використовуючи властивість `animation`, ми можемо приєднати анімацію до елемента та вказати додаткові параметри.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +    /* застосувати анімацію "go-left-right" до еменета
```suggestion
    /* застосувати анімацію "go-left-right" до елемента
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Є багато статей про `@keyframes` та [датальна специфікація](https://drafts.csswg.org/css-animations/).
```suggestion
Є багато статей про `@keyframes` та [детальна специфікація](https://drafts.csswg.org/css-animations/).
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Ймовірно, `@keyframes` не знадобляться вам часто, хіба якщо на ваших сайтах все постійно рухається.
```suggestion
Ймовірно, `@keyframes` не знадобиться вам часто, хіба якщо на ваших сайтах все постійно рухається.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Більшість властивостей CSS можна анімувати, оскільки більшість із них є числовими значеннями. Наприклад, `width`, `color`, `font-size` є числами. Коли ви анімуєте їх, браузер поступово змінює ці числ
```suggestion
Більшість властивостей CSS можна анімувати, оскільки більшість із них є числовими значеннями. Наприклад, `width`, `color`, `font-size` всі є числами. Коли ви анімуєте їх, браузер поступово змінює ці числа кадр за кадром, створюючи плавний ефект.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +1. **Макет**: перерахувати геометрію, а потім положення кожного елемента
```suggestion
1. **Layout**: перерахувати геометрію, а потім положення кожного елемента
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +2. **Фарбування**: перерахувати, як все має виглядати на своїх місцях, включаючи фон, кольори,
```suggestion
2. **Paint**: перерахувати, як все має виглядати на своїх місцях, включаючи фон, кольори,
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +3. **Композиція**: відтворити кінцеві результати в пікселях на екрані, застосувати CSS-перетворення, якщо вони існують.
```suggestion
3. **Composite**: відтворити кінцеві результати в пікселях на екрані, застосувати CSS-перетворення, якщо вони існують.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Під час CSS-анімації цей процес повторюється для кожного кадра. Однак властивості CSS, які ніколи не впливають на геометрію або положення, наприклад, `color`, можуть пропускатись кроці макета. Якщо `
```suggestion
Під час CSS-анімації цей процес повторюється для кожного кадра. Однак властивості CSS, які ніколи не впливають на геометрію або положення, наприклад, `color`, можуть пропускатись крок Layout. Якщо `color` змінюється, браузер не обчислює нову геометрію, він переходить до кроків Paint -> Composite. І є кілька властивостей, які безпосередньо переходять до Composite. Ви можете знайти довший список властивостей CSS та на яких етапах вони запускаються тут <https://csstriggers.com>.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Обчислення може зайняти багато часу, особливо на сторінках із великою кількістю елементів і складним макетом. І затримки фактично помітні на більшості пристроїв, що призводить до «тривожності», менш
```suggestion
Обчислення може зайняти багато часу, особливо на сторінках із великою кількістю елементів і складною структурою. І затримки фактично помітні на більшості пристроїв, що призводить до "тремтіння", менш плавної анімації.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Анімація властивостей, які пропускають крок макета, швидше. Навіть ліпше, ніж у випадку з пропусканням кроку фарбування.
```suggestion
Анімація властивостей, які пропускають Layout крок, працюють швидше. Навіть ліпше, ніж коли пропускається крок Paint.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +...Тому браузери застосовують `transform` "попереду" наявних обчислень Макету та Фарбування на етапі Композиції.
```suggestion
...Тому браузери застосовують `transform` після наявних обчислень Layout та Paint на кроці Composite.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Іншими словами, браузер обчислює макет (розміри, положення), розфарбовує його за допомогою colors, background тощо на етапі Фарбування, а потім застосовує `transform` до блоків елементів, які цього п
```suggestion
Іншими словами, браузер обчислює макет (розміри, положення), розфарбовує його за допомогою colors, background тощо на етапі Paint, а потім застосовує `transform` до елементів, які цього потребують.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Зміни (анімації) властивості `transform` ніколи не запускають кроки Макет та Фарбування. Більше того, браузер використовує графічний прискорювач (спеціальний чіп на ЦП або відеокарті) для CSS-перетво
```suggestion
Зміни (анімації) властивості `transform` ніколи не запускають кроки Layout та Paint. Більше того, браузер використовує графічний прискорювач (спеціальний чіп на ЦП або відеокарті) для CSS-перетворень, що робить їх дуже ефективними.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +На щастя, властивість `transform` дуже потужна. Використовуючи `transform` для елемента, ви можете обертати та повертати його, розтягувати та зменшувати, переміщувати та [багато іншого](https://devel
```suggestion
На щастя, властивість `transform` дуже потужна. Використовуючи `transform` для елемента, ви можете обертати та крутити його, розтягувати та зменшувати, переміщувати та [багато іншого](https://developer.mozilla.org/docs/Web/CSS/transform#syntax ). Тому замість властивостей `left/margin-left` ми можемо використовувати `transform: translateX(…)`, `transform: scale` для збільшення розміру елемента, тощо.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Властивість `opacity` ніколи не запускає Макет (в Mozilla Gecko також пропускається Фарбування). Ми можемо використовувати його для ефектів відображення/приховування або посилення/згасання.
```suggestion
Властивість `opacity` ніколи не запускає Layout (в Mozilla Gecko також пропускається Paint). Ми можемо використовувати його для ефектів відображення/приховування або посилення/згасання.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Поєднання `transform` з `opacity` зазвичай може вирішувати більшість наших потреб, забезпечуючи плавну, гарну анімацію.
```suggestion
Поєднання `transform` з `opacity` зазвичай може вирішувати більшість наших потреб, забезпечуючи плавну, яскраву анімацію.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Вона гарна для більшості завданнь анімації. Ми також можемо використовувати JavaScript для анімації, цьому присвячений наступний розділ.
```suggestion
Це підходить для більшості задач. Ми також можемо використовувати JavaScript для анімації, цьому присвячений наступний розділ.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +Анімація CSS дозволяє плавно (або покроково) анімувати зміну однієї або кількох властивостей CSS.
```suggestion
CSS-анімація дозволяє плавно (або покроково) анімувати зміну однієї або кількох властивостей CSS.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> ++ Швидка та легкиа для процесора.
```suggestion
+ Швидка та легка для процесора.
```

2022-07-19 10:30 UTC, stas-dolgachov commented on 7-animation/2-css-animations/article.md
> +- Анімації JavaScript є гнучкими. Вони можуть реалізувати будь-яку логіку анімації, навіть «вибух» елемента.
```suggestion
- Анімації JavaScript є гнучкими. Вони можуть реалізувати будь-яку логіку анімації, навіть "вибух" елемента.
```

2022-07-21 02:45 UTC, astropsy999 commented
/done

2022-07-22 06:11 UTC, astropsy999 reviewed
/done

2022-07-28 12:27 UTC, astropsy999 reviewed
/done

2022-08-04 08:04 UTC, stas-dolgachov approved these changes

2022-08-04 08:05 UTC, merged