translation: mutation observer
javascript-tutorial/uk.javascript.info pull request #372
Opened 2022-07-17 17:15 UTC by AdriandeCita

2022-07-17 17:20 UTC, AdriandeCita commented
Згадав, що у вас тут було прийнято замість апострофа використовували одинарну праву лапку. Це досі актуально, чи мій "стандартний" апостроф теж згодиться?

2022-07-19 10:47 UTC, stas-dolgachov commented
@AdriandeCita дякую за переклад, стандартний апостроф підійде :) Дивлюся :)

2022-07-19 12:01 UTC, stas-dolgachov requested changes
Дякую за чудовий переклад!
Подивіться, будь ласка, мої коментарі, напишіть мені, якщо не згодні з чимось :)

2022-07-23 07:53 UTC, AdriandeCita commented on 2-ui/99-ui-misc/01-mutation-observer/article.md
> +`MutationObserver` -- це вбудований об'єкт, який спостерігає за елементом DOM і викликає функцію зворотного виклику кожного разу, коли він помічає зміну.
FYI, ви пропонуєте замінити стандартний апостроф на символ правої одинарної лапки.
`'` - https://unicode-table.com/en/0027/
`’` - https://unicode-table.com/en/2019/

Загалом я не проти, просто це виглядає дивним

2022-07-23 07:58 UTC, AdriandeCita commented
@stas-dolgachov прийняв усі зауваження, окрім лапок. Стосовно них я залишив коментар вище :slightly_smiling_face:

2022-08-04 08:05 UTC, stas-dolgachov approved these changes

2022-08-04 08:06 UTC, stas-dolgachov commented
Згоден, щодо апострофу. Думаю, ми спробуємо найближчим часом привести все до ладу у цьому питанні якось автоматично :) Дякую, за ваш внесок!

2022-08-04 08:06 UTC, stas-dolgachov approved these changes

2022-08-04 08:07 UTC, stas-dolgachov commented
#1

2022-08-04 08:09 UTC, stas-dolgachov commented
[Mutation observer](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/2-ui/99-ui-misc/01-mutation-observer)

2022-08-04 08:09 UTC, merged