fix: code block; add missing translations;
javascript-tutorial/uk.javascript.info pull request #373
Opened 2022-07-23 22:10 UTC by git-antonyuk

2022-07-23 22:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=373) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=373) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=373) it.</sub>

2022-08-04 08:25 UTC, stas-dolgachov requested changes

2022-08-04 08:25 UTC, stas-dolgachov commented on 1-js/05-data-types/06-iterable/article.md
> +Доречі, ми можемо створити `slice`, якій підтримує сурогатні пари:
```suggestion
До речі, ми можемо створити `slice`, якій підтримує сурогатні пари:
```
Я не впевнений, що так правильно, але інтернет каже, що так :)

2022-08-04 15:47 UTC, git-antonyuk commented on 1-js/05-data-types/06-iterable/article.md
> +Доречі, ми можемо створити `slice`, якій підтримує сурогатні пари:
Певно за новими правилами так і є :)

2022-08-04 15:47 UTC, git-antonyuk commented on 1-js/05-data-types/06-iterable/article.md
> +Доречі, ми можемо створити `slice`, якій підтримує сурогатні пари:
![Mova_10](https://user-images.githubusercontent.com/17859567/182890317-b0f4ae10-fb88-4f70-a4a7-fd7eb8c39804.png)

2022-08-04 15:52 UTC, git-antonyuk commented
/done

2022-08-11 11:06 UTC, merged