translation: Anchors: string start ^ and end $
javascript-tutorial/uk.javascript.info pull request #376
Opened 2022-07-24 21:09 UTC by git-antonyuk

2022-08-04 08:21 UTC, stas-dolgachov commented
#1

2022-10-06 10:20 UTC, git-antonyuk commented
@stas-dolgachov чому ми не мержимо переклад?

2022-10-12 09:27 UTC, stas-dolgachov requested changes
Дякую, за чудовий переклад!
Вибачаюсь, що так довго перевіряв.
Наступного разу все буде набагато швидше =)

2022-10-12 09:27 UTC, stas-dolgachov commented on 9-regular-expressions/04-regexp-anchors/article.md
> +У мові регулярних виразів це так `pattern:\d\d:\d\d`:
```suggestion
У мові регулярних виразів це виглядає так `pattern:\d\d:\d\d`:
```

2022-10-12 09:27 UTC, stas-dolgachov commented on 9-regular-expressions/04-regexp-anchors/article.md
> +Якорі `pattern:^` та `pattern:$` - це перевірки. В них нульова ширина.
```suggestion
Якорі `pattern:^` та `pattern:$` -- це перевірки. В них нульова ширина.
```

2022-10-12 09:34 UTC, merged