Character Classes
javascript-tutorial/uk.javascript.info pull request #383
Opened 2022-08-24 12:23 UTC by AntonBurchak

2022-08-24 12:24 UTC, AntonBurchak commented
@stas-dolgachov Happy holiday! Please review it :)

2022-10-05 10:46 UTC, stas-dolgachov requested changes
Привіт, дякую за чудовий переклад! Подивись, бум ласка, мої коментарі :)

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
>  # Character classes
Може заголовок такоже перекласти?

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +*Символьний клас* – це спеціальне позначення, яке відповідає будь-якому символу певного набору.
```suggestion
*Символьний клас* -- це спеціальне позначення, яке відповідає будь-якому символу з певного набору.
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +// давайте зробимо з них номер телефону лише цифрами:
```suggestion
// давайте зробимо з них номер телефону лише з цифр:
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +: Символ «слова» – літера латинського алфавіту, цифра або підчеркування `_`. Нелатинські літери (наприклад, кирилиця чи хінді) не належать до `pattern:\w`.
```suggestion
: Символ "слова" -- літера латинського алфавіту, цифра або символ підкреслення `_`. Нелатинські літери (наприклад, кирилиця чи хінді) не належать до `pattern:\w`.
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +: Будь-який символ, окрім `pattern:\w`, тобто не букви з латиниці, не знак підкреслення і цифра.
```suggestion
: Будь-який символ, окрім `pattern:\w`, тобто не букви з латиниці, не символ підкреслення і цифра.
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Альтернативний, коротший шлях – знайти нецифрові символи `pattern:\D` і видалити їх з рядка:
```suggestion
Альтернативний, коротший шлях -- знайти нецифрові символи `pattern:\D` і видалити їх з рядка:
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +## Крапка – це будь-який символ
```suggestion
## Крапка -- це будь-який символ
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Крапка `pattern:.` – це спеціальний символьний клас, який відповідає "будь-якому символу, крім нового рядка".
```suggestion
Крапка `pattern:.` -- це спеціальний символьний клас, який відповідає "будь-якому символу, крім символу нового рядка".
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +На щастя, є альтернатива, яка працює всюди. Ми можемо використовувати регулярний вираз, як-от `pattern:[\s\S]`, щоб відповідати "будь-якому символу" (цей шаблон буде описано в статті <info:regexp-cha
```suggestion
На щастя, є альтернатива, яка працює всюди. Ми можемо використовувати регулярний вираз, як-от `pattern:[\s\S]`, щоб знаходити "будь-який символ" (цей шаблон буде описано в статті <info:regexp-character-sets-and-ranges>).
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Також ми можемо використати цей спосіб, якщо хочемо, щоб обидва типи "крапок" були в одному шаблоні: наявний шаблон `pattern:.` крапки, який поводиться звичайним способом ("без нового рядка"), а тако
```suggestion
Також ми можемо використати цей прийом, якщо хочемо, щоб обидва типи "крапок" були в одному шаблоні: наявний шаблон `pattern:.` крапки, який поводиться звичайним чином ("без нового рядка"), а також відповідності "будь-якому символу" з `pattern:[\s\S]` або подібним.
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Зазвичай ми приділяємо мало уваги пробілам. Для нас рядки `subject:1-5` і `subject:1-5` майже ідентичні.
```suggestion
Зазвичай ми приділяємо мало уваги пробілам. Для нас рядки `subject:1-5` і `subject:1 - 5` майже ідентичні.
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +Але якщо регулярний вираз не враховує пробіли, він може не працювати.
```suggestion
Але якщо регулярний вираз не враховує пробіли, він може не спрацювати.
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
> +**Пробіл – це символ. Такий же важливий, як і будь-який інший.**
```suggestion
**Пробіл -- це символ. Так само важливий, як і будь-який інший.**
```

2022-10-05 10:46 UTC, stas-dolgachov commented on 9-regular-expressions/02-regexp-character-classes/article.md
>  ## Summary
```suggestion
## Підсумки
```

2022-10-06 20:52 UTC, AntonBurchak commented
/done

2022-10-12 08:55 UTC, merged