Alternation (OR) |
javascript-tutorial/uk.javascript.info pull request #388
Opened 2022-09-17 20:16 UTC by vladiuskor

2022-09-17 20:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=388) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=388) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=388) it.</sub>

2022-10-21 13:21 UTC, stas-dolgachov requested changes
Дякую, за чудовий переклад! Вибачаюсь, що вам довелося так довго чекати :)
Подивіться, будь ласка, мої коментарі і напишіть мені, якщо з чимось не згодні.

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/article.md
> +Альтернація - це термін у регулярному виразі, який насправді є простим "АБО".
```suggestion
Альтернація -- це термін у регулярному виразі, який насправді є простим "АБО".
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/article.md
> +- `pattern:gr(a|e)y` означає те саме, що і `pattern:gr[ae]y`.
```suggestion
- `pattern:gr(a|e)y` означає те саме, що й `pattern:gr[ae]y`.
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/article.md
> +Для того, щоб використати альтернацію до обраної частини шаблону, ми можемо загорнути його у дужки:
```suggestion
Для того, щоб використати альтернацію з обраною частиною шаблону, ми можемо загорнути його у дужки:
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/article.md
> +У попередніх главах було завдання написати регулярний вираз для пошуку часу у форматі `гг:хх`, наприклад `12:00`. Однак простий шаблон `pattern:\d\d:\d\d` недостатньо точний. Він приймає `25:99` як ч
```suggestion
У попередніх статтях було завдання написати регулярний вираз для пошуку часу у форматі `гг:хх`, наприклад `12:00`. Однак простий шаблон `pattern:\d\d:\d\d` недостатньо точний. Він приймає `25:99` як час (99 хвилин підходять до шаблону, однак цей час не є вірним).
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/task.md
> +ВВ-код має вигляд `[tag]...[/tag]`, де `tag` - це один з: `b`, `url` або `quote`.
```suggestion
ВВ-тег має вигляд `[tag]...[/tag]`, де `tag` --це один з: `b`, `url` або `quote`.
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/task.md
> +ВВ-коди можуть бути вкладеними. Але тег не може бути вкладеним сам у себе, наприклад:
```suggestion
ВВ-теги можуть бути вкладеними. Але тег не може бути вкладеним сам у себе, наприклад:
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/task.md
> +Створіть регулярний вираз для пошуку всіх BB-кодів та їх вмісту.
```suggestion
Створіть регулярний вираз для пошуку всіх BB-тегів та їх вмісту.
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/task.md
> +let regexp = /ваш регулярний вираз/прапорець;
```suggestion
let regexp = /ваш регулярний вираз/прапорці;
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/task.md
> +Якщо теки вкладені, тоді необхідно шукати зовнішній тег (за бажанням, можна продовжити пошук всередині його вмісту):
```suggestion
Якщо теги вкладені, тоді необхідно шукати зовнішній тег (за бажанням, можна продовжити пошук всередині його вмісту):
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/task.md
> +let regexp = /ваш регулярний вираз/прапорець;
```suggestion
let regexp = /ваш регулярний вираз/прапорці;
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/03-match-quoted-string/solution.md
> +Вирішення: `pattern:/"(\\.|[^"\\])*"/g`.
```suggestion
Рішення: `pattern:/"(\\.|[^"\\])*"/g`.
```

2022-10-21 13:21 UTC, stas-dolgachov commented on 9-regular-expressions/13-regexp-alternation/03-match-quoted-string/task.md
> +У цьому і полягає основна складність завдання, адже без цієї умови - вирішення було б елементарним.
```suggestion
У цьому і полягає основна складність завдання, адже без цієї умови -- рішення було б елементарним.
```

2022-10-23 20:54 UTC, vladiuskor commented
/done

2022-10-23 20:58 UTC, vladiuskor commented
> Дякую, за чудовий переклад! Вибачаюсь, що вам довелося так довго чекати :) Подивіться, будь ласка, мої коментарі і напишіть мені, якщо з чимось не згодні.

Дякую за можливість зробити внесок у розвиток чудового ресурсу для україномовної спільноти. Згідний з усіма правками.)

2022-10-24 12:29 UTC, stas-dolgachov commented
@all-contributors add @vladiuskor for translation

2022-10-24 12:30 UTC, stas-dolgachov approved these changes

2022-10-24 12:30 UTC, merged