Element size and scrolling
javascript-tutorial/uk.javascript.info pull request #401
Opened 2022-10-21 15:11 UTC by 80001

2022-10-21 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=401) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=401) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=401) it.</sub>

2022-10-30 20:01 UTC, stas-dolgachov requested changes
Дякую за чудовий переклад! Подивіться, будь ласка, мої коментарі. 
Наступного разу за можливістю, будь ласка робіть один пулл реквест на одну статтю. 
Так простіше все зібрати до купи

2022-10-30 20:01 UTC, stas-dolgachov commented on 2-ui/1-document/09-size-and-scroll/article.md
> +## Висновок
```suggestion
## Підсумки
```

2022-11-01 09:52 UTC, 80001 reviewed
/done

2022-11-01 13:56 UTC, stas-dolgachov approved these changes

2022-11-01 14:00 UTC, stas-dolgachov commented
@all-contributors add @80001 for translation

2022-11-01 14:00 UTC, merged