Update solution.md
javascript-tutorial/uk.javascript.info pull request #403
Opened 2022-10-21 15:50 UTC by 80001

2022-10-30 20:04 UTC, stas-dolgachov requested changes

2022-10-30 20:04 UTC, stas-dolgachov commented on 2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/solution.md
> +Іншими словами: (вся висота) мінус (прокручена верхня частина) мінус (видима частина) -- саме це прокручена нижня частина.
```suggestion
Іншими словами: (вся висота) мінус (прокручена верхня частина) мінус (видима частина) -- саме це і є прокручена нижня частина.
```

2022-11-01 09:51 UTC, 80001 reviewed
/done

2022-11-01 13:56 UTC, stas-dolgachov approved these changes

2022-11-01 14:01 UTC, merged