Update task.md
javascript-tutorial/uk.javascript.info pull request #405
Opened 2022-10-21 15:56 UTC by 80001

2022-10-30 20:07 UTC, stas-dolgachov requested changes

2022-10-30 20:07 UTC, stas-dolgachov commented on 2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
> +
```suggestion

```

2022-10-30 20:07 UTC, stas-dolgachov commented on 2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
> +P.S. Код повинен працювати для будь-якого HTML-документа, не залежно від його вмісту.
```suggestion
P.S. Код повинен працювати для будь-якого HTML-документа, незалежно від його вмісту.
```

2022-11-01 09:46 UTC, 80001 commented on 2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
> +P.S. Код повинен працювати для будь-якого HTML-документа, не залежно від його вмісту.
/done

2022-11-01 09:49 UTC, 80001 reviewed
/done

2022-11-01 13:57 UTC, stas-dolgachov approved these changes

2022-11-01 14:01 UTC, merged