Patterns and flags
javascript-tutorial/uk.javascript.info pull request #488
Opened 2023-04-25 13:58 UTC by bromotdi

2023-04-25 13:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=488) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=488) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=488) it.</sub>

2023-04-26 20:58 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +regexp = /шаблон/gmi; // з прапорами gmi (будуть описані далі)
```suggestion
regexp = /шаблон/gmi; // з прапорами g,m та i (будуть описані далі)
```

2023-04-26 21:04 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +let regexp = new RegExp(`<${tag}>`); // те саме, що /<h2>/ при відповіді "h2" на prompt вище
```suggestion
let regexp = new RegExp(`<${tag}>`); // те саме, що /<h2>/ при відповіді "h2" на запит вище
```

2023-04-26 21:08 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- регулярний вираз - `pattern: червоний`
```suggestion
- регулярний вираз - `pattern:червоний`
```

2023-04-26 21:08 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- результат -- `match: зелений`
```suggestion
- результат -- `match:зелений`
```

2023-04-26 21:14 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +В рядке заміни `replacement` ми можемо використовувати спеціальні комбінації символів для вставки фрагментів збігу:
```suggestion
У рядку заміни `replacement` ми можемо використовувати спеціальні комбінації символів для вставки фрагментів збігу:
```

2023-04-26 21:15 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +alert( "Люблю HTML".replace(/HTML/, "$& і JavaScript") ); // Люблю HTML та JavaScript
```suggestion
alert( "Люблю HTML".replace(/HTML/, "$& і JavaScript") ); // Люблю HTML і JavaScript
```

тут або і там і там "і", або "та"

2023-04-26 21:16 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +alert(regexp.test(str)); // true
```suggestion
alert( regexp.test(str) ); // true
```

2023-04-26 21:17 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +## Разом
```suggestion
## Підсумки
```

2023-04-26 21:19 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- Метод `str.match(regexp)` шукає збіги: всі, якщо є прапор `pattern: g`, інакше тільки перше.
```suggestion
- Метод `str.match(regexp)` шукає збіги: всі, якщо є прапор `pattern:g`, інакше тільки перше.
```

2023-04-26 21:20 UTC, alexgalkin commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- Метод `str.replace(regexp, replacement)` замінює збіги з `regexp` на `replacement`: всі, якщо у регулярного виразу є прапор `pattern: g`, інакше тільки перше.
```suggestion
- Метод `str.replace(regexp, replacement)` замінює збіги з `regexp` на `replacement`: всі, якщо у регулярного виразу є прапор `pattern:g`, інакше тільки перший.
```

2023-04-26 22:38 UTC, bromotdi commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- Метод `str.replace(regexp, replacement)` замінює збіги з `regexp` на `replacement`: всі, якщо у регулярного виразу є прапор `pattern: g`, інакше тільки перше.
Дякую за слушні виправлення, надалі буду більш обачна

2023-04-28 22:25 UTC, alexgalkin approved these changes

2023-04-29 17:56 UTC, tarasyyyk requested changes

2023-04-29 17:56 UTC, tarasyyyk commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- Регулярний вираз складається з шаблону і необов'язкових прапорів: `pattern: g`, `pattern: i`, `pattern: m`, `pattern: u`, `pattern: s`, `pattern: y`.
```suggestion
- Регулярний вираз складається з шаблону і необов’язкових прапорів: `pattern:g`, `pattern:i`, `pattern:m`, `pattern:u`, `pattern:s`, `pattern:y`.
```

2023-04-29 18:39 UTC, bromotdi commented
/done

2023-04-30 18:02 UTC, tarasyyyk approved these changes

2023-04-30 18:03 UTC, merged

2023-04-30 18:06 UTC, tarasyyyk commented
@all-contributors please add @bromotdi for translation

2023-04-30 18:09 UTC, tarasyyyk commented
Дякую за переклад, @bromotdi !
Додав вас в почесний список учасників перекладу цього посібника🙂
Можете глянути на себе красуню😉