Update article.md
javascript-tutorial/uk.javascript.info pull request #491
Opened 2023-05-13 09:07 UTC by kopijka

Переклад на українську мову
13,05,23

2023-05-13 09:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=491) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/uk.javascript.info?pullRequest=491) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/uk.javascript.info?pullRequest=491) it.</sub>

2023-05-13 18:16 UTC, SuperMaxusa commented on 5-network/01-fetch/article.md
> +Наприклад, можна використовувати мережовий запит, щоб:
```suggestion
Наприклад, можна використовувати мережевий запит, щоб:
```

2023-05-13 18:37 UTC, SuperMaxusa requested changes

2023-05-13 18:37 UTC, SuperMaxusa commented on 5-network/01-fetch/article.md
> +Проміс закінчуєся помилкою, якщо `fetch` не зміг виконати HTTP-запит, e.g. наприклад, під час помилки мережі або якщо такий сайт відсутний. HTTP-статуси 404 та 500 це не помилка.
```suggestion
Проміс закінчується помилкою, якщо `fetch` не зміг виконати HTTP-запит, наприклад, через помилку мережі або, якщо такого сайту не існує. Неправильні HTTP-статуси, як 404 та 500, не викликатимуть помилку.
```

2023-05-13 18:37 UTC, SuperMaxusa commented on 5-network/01-fetch/article.md
> +Без `options`, це просто GET запит, котрий скачує вміс за адресою `url`.
```suggestion
Без `options`, це просто GET запит, який завантажує зміст за адресою `url`.
```

2023-05-13 18:37 UTC, SuperMaxusa commented on 5-network/01-fetch/article.md
> +Процес отримання запиту зазвичай відбуваєся у два етапи.
```suggestion
Процес отримання запиту зазвичай відбувається у два етапи.
```

2023-05-13 18:37 UTC, SuperMaxusa commented on 5-network/01-fetch/article.md
> +  // отримання тіла запиту (див. про цей метод нище)
```suggestion
  // отримання тіла запиту (див. про цей метод нижче)
```

2023-05-13 18:37 UTC, SuperMaxusa commented on 5-network/01-fetch/article.md
> +// створення <img> для ного
```suggestion
// створення <img> для нього
```

2023-05-13 18:37 UTC, SuperMaxusa commented on 5-network/01-fetch/article.md
> +- `response.status` -- HTTP код відповід,
```suggestion
- `response.status` -- HTTP код відповіді,
```

2023-06-02 11:26 UTC, stas-dolgachov requested changes
Дякую, за переклад! Я написав кілька коментарів, я сам їх додам до вашого пулл реквеста і прийму його.
Проте, щоб повністю завершити переклад цієї статті потрібно перекласти задачу, яка знаходиться поряд із нею. 

Якщо вам нескладно, зробіть ще один пулл реквест із цим перекладом.

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +`Response`представляє декілька методів, котрі грунтуются на промісах, для доступу до тіла запиту в різних форматах:
```suggestion
`Response` надає декілька методів, які повертають проміс, для доступу до тіла запиту в різних форматах:
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +- **`response.formData()`** -- повертає відповідь, як `FormData` object (він буде розглянутий [у наптупному розділі](info:formdata)),
```suggestion
- **`response.formData()`** -- повертає відповідь, як об'єкт `FormData` (він буде розглянутий [у наступному розділі](info:formdata)),
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +- **`response.blob()`** -- повертає об'єкт, як[Blob](info:blob) (бінарні дані з типом),
```suggestion
- **`response.blob()`** -- повертає відповідь, як [Blob](info:blob) (бінарні дані з типом),
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +- крім того, `response.body` це об'єкт [ReadableStream](https://streams.spec.whatwg.org/#rs-class) ,за допомогою котрого можна отримувати (зчитувати) тіло частинами. Такий приклад буде розглянуто тро
```suggestion
- крім того, `response.body` це об'єкт [ReadableStream](https://streams.spec.whatwg.org/#rs-class), за допомогою якого можна отримувати (зчитувати) тіло відповіді частинами. Такий приклад буде розглянуто трохи пізніше.
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Наприклад, буде отримано JSON-об'єкт з останніми комітами із ропозиторію GitHub:
```suggestion
Наприклад, буде отримано JSON-об'єкт з останніми комітами із репозиторію GitHub:
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Для прикладу роботи із бінарними даними, буде зроблено запит та виведено на екран логотип [специфікації "fetch"](https://fetch.spec.whatwg.org) (див. розділ [Blob](info:blob), дізнатися про операції
```suggestion
Для прикладу роботи із бінарними даними, буде зроблено запит та виведено на екран логотип [специфікації "fetch"](https://fetch.spec.whatwg.org) (див. розділ [Blob](info:blob), щоб дізнатись детальніше про операції із `Blob`):
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +let blob = await response.blob(); // скачано, як Blob об'єкт
```suggestion
let blob = await response.blob(); // скачати, як Blob об'єкт
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Якщо, було отримано відповід із `response.text()`, тоді `response.json()` не зпрацює, бо дані вже були оброблені..
```suggestion
Якщо, було отримано відповід із `response.text()`, тоді `response.json()` не спрацює, бо дані вже були оброблені..
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
>  let text = await response.text(); // response body consumed
```suggestion
let text = await response.text(); // читаємо тіло відповіді
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
>  let parsed = await response.json(); // fails (already consumed)
```suggestion
let parsed = await response.json(); // завершується помилкою, бо дані вже прочитані
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +## Заголовки запиту
```suggestion
## Заголовки відповіді
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Заоголовки запиту зберігаются у схожому на  Map об'єкті `response.headers`.
```suggestion
Заоголовки відповіді зберігаются у схожому на Map об'єкті `response.headers`.
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Це не зовсім `Map`, але можна використати такі самі методи, як із `Map`, щоб отримати заголовок за його назвою або перебрати заголовки у циклі:
```suggestion
Це не зовсім `Map`, але можна використовувати такі самі методи, щоб отримати заголовок за його назвою або перебрати заголовки у циклі:
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Для встановлення заголовка запиту в `fetch`, можна використати опцію `headers` option. Вона містит об'єкт з вихідними заголовками, наприклад:
```suggestion
Для встановлення заголовка запиту в `fetch`, можна використати властивість `headers` в об'єкті `options`. Вона містит об'єкт з вихідними заголовками, наприклад:
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +...Є список [заборонені заголовки HTTP](https://fetch.spec.whatwg.org/#forbidden-header-name), котрі не можна встановити:
```suggestion
...Але існує список [заборонених HTTP заголовків](https://fetch.spec.whatwg.org/#forbidden-header-name), які не можна встановити:
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Ці заголовки забезпечуют достовірність HTTP, через то вони контролюются тільки браузером.
```suggestion
Ці заголовки забезпечуют достовірність HTTP, через це вони контролюются і встановлюються лише браузером.
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +- **`body`** -- тіло запиту, одне із списку:
```suggestion
- **`body`** -- тіло запиту, щось одне із списку:
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Зауваження, що оскільки тіло запиту `body` - це рядок, то заголовок `Content-Type` по замовчуванню буде `text/plain;charset=UTF-8` .
```suggestion
Зверніть увагу, якщо тіло запиту `body` -- рядок, то заголовок `Content-Type` типово буде `text/plain;charset=UTF-8` .
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Але, оскільки надіслано JSON, то використано парамет `headers` для відправлення замість цього `application/json`, правильний `Content-Type` для JSON формату.
```suggestion
Але, оскільки ми надсилаємо дані у форматі JSON, то через `headers` ми маємо встановити значення `application/json` -- правильний `Content-Type` для JSON формату.
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Зауваження, тут не потрібно вручну встановлювати заголовок `Content-Type`, бо об'єкт `Blob` вбудований тип (тут `image/png`, котрий заданий у `toBlob`). Під час відправлення об'єктів `Blob`, він авто
```suggestion
Зауваження, тут не потрібно вручну встановлювати заголовок `Content-Type`, бо об'єкт `Blob` вбудований тип (буде використано `image/png`, заданий через `toBlob`). Під час відправлення об'єктів `Blob`, він автоматично стає значенням `Content-Type`.
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +## Підсумок
```suggestion
## Підсумки
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Типовий запит за домогою `fetch` складаєся із двох операторів `await`:
```suggestion
Типовий запит за допомогою `fetch` складаєся із двох операторів `await`:
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +Опції `fetch`, котрі на даний момент вивчено:
```suggestion
Опції `fetch`, які ми розглянули:
```

2023-06-02 11:26 UTC, stas-dolgachov commented on 5-network/01-fetch/article.md
> +- `headers` -- об'єкт із запитуваними заголовками (не всі заголовки дозволені),
```suggestion
- `headers` -- об'єкт із заголовками запиту (не всі заголовки дозволені),
```

2023-06-02 11:26 UTC, stas-dolgachov requested changes
Дякую, за переклад! Я написав кілька коментарів, я сам їх додам до вашого пулл реквеста і прийму його.
Проте, щоб повністю завершити переклад цієї статті потрібно перекласти задачу, яка знаходиться поряд із нею. 

Якщо вам нескладно, зробіть ще один пулл реквест із цим перекладом.

2023-06-02 11:34 UTC, stas-dolgachov approved these changes
Done

2023-06-02 11:34 UTC, merged