fix,traslate(2-1.5): Fix and traslate `Node properties: type, tag and contents` article
javascript-tutorial/uk.javascript.info pull request #530
Opened 2023-07-19 13:45 UTC by ltlaitoff

Fixed translation errors

Synced `dom-class-hierarchy.svg` with original version and translated
Synchronized explanation of base classes and traslated

2023-07-27 11:29 UTC, kester36 requested changes

2023-07-27 11:29 UTC, kester36 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Найбільш стандартні атрибути HTML мають відповідну DOM-властивість, і ми можемо отримати доступ до нєї.
```suggestion
Найбільш стандартні атрибути HTML мають відповідну DOM-властивість, і ми можемо отримати доступ до неї.
```

2023-07-27 11:29 UTC, kester36 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +: Використовується для визначення, чи є вузол текстовим чи елементним вузлом. Має числове значення: `1` для елементів, `3` для текстових вузлів та декілька інших значень для інших типів вузлів. Тільк
Pay attention:
You've translated `Лише` to `Тільки` here, but not in the next row.
Maybe it is better to use the same word in both rows.

2023-07-27 11:29 UTC, kester36 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +: Текст всередині елемента: HTML мінус усі `<теги>`. Записуючи в нього, ми отримуємо текст всередині елемента, з усіма спеціальними символами та тегами, трактованими як текст. Це безпечний спосіб вст
```suggestion
: Текст всередині елемента: HTML мінус усі `<теги>`. Записуючи в нього, ми отримуємо текст всередині елемента, з усіма спеціальними символами та тегами, трактованими як текст. Дозволяє безпечно вставляти користувацький текст, захищаючи від небажаних вставок HTML.
```

2023-07-29 11:44 UTC, ltlaitoff commented
@kester36 Thanks for the review. It's really very useful for creating a good book in Ukrainian about JavaScript.

2023-07-29 11:45 UTC, ltlaitoff commented
/done

2023-07-29 14:02 UTC, kester36 approved these changes

2023-08-07 11:34 UTC, stas-dolgachov approved these changes

2023-08-07 11:34 UTC, merged