Додавання розділу: WeakRef and FinalizationRegistry
javascript-tutorial/uk.javascript.info pull request #576
Opened 2023-11-06 15:08 UTC by WOLFRIEND

## Опис
Додавання перекладу статті: [WeakRef і FinalizationRegistry](https://learn.javascript.ru/weakref-finalizationregistry).

## Пов'язані Issue
- Початкове обговорення та затвердження: https://github.com/javascript-tutorial/ru.javascript.info/issues/1898.
- Мій початковий pull request RUS версії статті: https://github.com/javascript-tutorial/ru.javascript.info/pull/1899.

2023-11-06 15:09 UTC, WOLFRIEND commented
Привіт.
Як і обіцяв, ось переклад моєї статті [WeakRef и FinalizationRegistry](https://learn.javascript.ru/weakref-finalizationregistry) на українську мову.
Якщо потрібні будь-які зміни чи виправлення, повідомте мене. Буду вдячний за коментарі.
Заздалегідь дякую.

2023-11-08 14:30 UTC, dolgachio commented
@WOLFRIEND добрий день, підкажіть, чи планується англійська версія цієї статті?

2023-11-08 14:59 UTC, WOLFRIEND commented
> @WOLFRIEND добрий день, підкажіть, чи планується англійська версія цієї статті?

@dolgachio 
Вітаю.
Звичайно ж, роботу з перекладу англійською мовою вже зроблено мною і відправлено на розгляд. Ось посилання на мій pull request: https://github.com/javascript-tutorial/en.javascript.info/pull/3609.
Якщо ви можете якось допомогти з тим, щоб його швидше розглянули, буду вам дуже вдячний.

2023-11-08 15:01 UTC, dolgachio commented
Дякую, вже побачив. Як вони його розглянуть, ми також поревьюваємо і вмерджимо.

2023-11-15 20:14 UTC, WOLFRIEND commented
@dolgachio 
Добрий вечір.
Англійська версія була змерджена та опублікована.
Чи могли б ви, будь ласка, розглянути цей pull request?
Дякую.

2023-12-04 13:30 UTC, WOLFRIEND commented
@dolgachio

2024-02-21 12:46 UTC, dolgachio commented
@WOLFRIEND доброго дня, оновіть, будь ласка свій пілл реквест на останній мастер. Після синхронізації з англійською версією, теперь там видає конфлікти. Скоріш за все, вам просто треба обрати зміни, які тут зроблені, над тими, що ідуть з мастера.

2024-02-21 13:15 UTC, WOLFRIEND commented
> @WOLFRIEND доброго дня, оновіть, будь ласка свій пілл реквест на останній мастер. Після синхронізації з англійською версією, теперь там видає конфлікти. Скоріш за все, вам просто треба обрати зміни, які тут зроблені, над тими, що ідуть з мастера.

Добридень. Оновив, подивіться, будь ласка, чи все гаразд?

2024-02-21 16:22 UTC, dolgachio commented
@WOLFRIEND наче все гаразд, дякую, продовжую ревью

2024-02-22 11:25 UTC, dolgachio requested changes
Через те що, кількість рядків а перекладі сильно відрізняється від статті в оригіналі, я буду додавати свої зміни поступово, щоб впевнитись, що все виправляється коректно.

2024-02-22 11:25 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/weakref-finalizationregistry.view/index.html
> +  <title>Photo Library Collage</title>
```suggestion
```

2024-02-22 11:25 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/weakref-finalizationregistry.view/index.html
>    <link rel="stylesheet" href="index.css">
```suggestion
  <link rel="stylesheet" href="index.css">
  <title>Photo Library Collage</title>
```

2024-02-22 11:25 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/weakref-dom.view/index.html
> +  <title>WeakRef DOM Логер</title>
```suggestion
```

2024-02-22 11:25 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/weakref-dom.view/index.html
>    <link rel="stylesheet" href="index.css">
```suggestion
  <link rel="stylesheet" href="index.css">
  <title>WeakRef DOM Логер</title>
```

2024-02-22 11:25 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Згадуючи основну концепцію *принципу досяжності* з розділу <info:garbage-collection> , ми можемо відзначити,
```suggestion

Згадуючи основну концепцію *принципу досяжності* з розділу <info:garbage-collection>, ми можемо відзначити,
```

2024-02-22 11:25 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +що двигун JavaScript гарантовано зберігає у пам'яті значення, які доступні або використовуються.
```suggestion
що рушій JavaScript гарантовано зберігає у пам'яті значення, які досяжні або використовуються.  
```

2024-02-22 11:25 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +// посилання втрачається і об'єкт буде видалено з пам'яті
```suggestion
// посилання втрачається і об'єкт буде видалено з пам'яті

```

2024-02-22 13:47 UTC, WOLFRIEND commented
> Через те що, кількість рядків а перекладі сильно відрізняється від статті в оригіналі, я буду додавати свої зміни поступово, щоб впевнитись, що все виправляється коректно.

Добре.
Чи потрібно мені в такому разі щось додатково підтверджувати чи ви можете внести зміни самостійно?
Якщо від мене потрібні якісь зміни чи допомога, дайте мені знати.
Дякую.

2024-02-23 12:54 UTC, dolgachio commented
@WOLFRIEND на даному етапі я сам внесу зміни, якщо щось знадобиться, я напишу

2024-02-23 18:42 UTC, dolgachio commented
#1 [WeakRef and FinalizationRegistry](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/1-js/99-js-misc/07-weakref-finalizationregistry)

2024-02-25 08:49 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
```suggestion


```

2024-02-25 08:49 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
>  ```
```suggestion
```

```

2024-02-25 08:49 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
```suggestion
```

2024-02-25 08:49 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Об'єкт `{ name: "John" }` видалився б із пам'яті тільки в разі відсутності сильних посилань на нього (якби ми також перезаписали значення змінної `admin`).
```suggestion
Об'єкт `{ name: "John" }` видалиться з пам'яті тільки в разі відсутності сильних посилань на нього (якби ми також перепризначили значення змінної `admin`).  
```

2024-02-25 08:52 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Або ж схожий, але трохи ускладнений код із двома сильними посиланнями:
```suggestion
```

Або ж схожий, але трохи ускладнений код із двома сильними посиланнями:
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Перш ніж ми перейдемо до вивчення, варто зазначити, що правильне застосування структур,
```suggestion
Перш ніж ми перейдемо до вивчення, варто зазначити, що правильне застосування структур, про які йтиметься в цій статті, вимагає дуже ретельного обмірковування, і якщо це можливо, їхнього використання краще уникати.
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +про які йтиметься в цій статті, вимагає дуже ретельного обмірковування, і якщо це можливо, їхнього використання краще уникати.
```suggestion
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +`WeakRef` - це об'єкт, що містить слабке посилання на інший об'єкт, який називається `target` або `referent`.
```suggestion
`WeakRef` - це об'єкт, що містить слабке посилання на інший об'єкт, який називається `target` або `referent`.
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +На схемі нижче зображено два типи посилань: сильне посилання з використанням змінної `user` і слабке посилання з використанням змінної `admin`:
```suggestion
На схемі нижче зображено два типи посилань: сильне посилання з використанням змінної `user` і слабке посилання з використанням змінної `admin`:
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Слабкого посилання на об'єкт недостатньо, щоб зберегти його "в живих".
```suggestion
Слабкого посилання на об'єкт недостатньо, щоб зберегти його "в живих". Коли лишаються тільки слабкі посилання, збирач сміття має право знищити цей об'єкт і використовувати його пам'ять для чогось іншого.
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Коли єдиними зоставшимися посиланнями на об'єкт-референт, є слабкі посилання, збирач сміття має право знищити цей об'єкт і використовувати його пам'ять для чогось іншого.
```suggestion
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Тобто наш об'єкт стає своєрідним "[котом Шредінгера](https://uk.wikipedia.org/wiki/%D0%9A%D1%96%D1%82_%D0%A8%D1%80%D0%B5%D0%B4%D1%96%D0%BD%D0%B3%D0%B5%D1%80%D0%B0)" - ми не можемо знати точно, "живий
```suggestion
Тобто наш об'єкт стає своєрідним "[котом Шредінгера](https://uk.wikipedia.org/wiki/Кіт_Шредінгера)" - ми не можемо знати точно, "живий" він чи "мертвий":  
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +На цьому етапі, щоб отримати об'єкт із екземпляра `WeakRef`, ми скористаємося його методом `deref()`.
```suggestion
На цьому етапі, щоб отримати об'єкт з екземпляру `WeakRef`, ми використаємо його `deref()` метод.  
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Якщо об'єкт було видалено збирачем сміття, - метод `deref()` поверне `undefined`:
```suggestion
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Метод `deref()` повертає об'єкт-референт, на який посилається `WeakRef`, якщо об'єкт все ще перебуває в пам'яті.
```suggestion
Метод `deref()` повертає об'єкт-референт, на який посилається `WeakRef`, якщо об'єкт все ще перебуває в пам'яті. Якщо об'єкт було видалено збирачем сміття, - метод `deref()` поверне `undefined`:
```

2024-02-25 09:14 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +`WeakRef` зазвичай використовується для створення кешів або
```suggestion
`WeakRef` зазвичай використовується для створення кешу або [асоціативних масивів](https://uk.wikipedia.org/wiki/Асоціативний_масив), де зберігаються великі об'єкти.
```

2024-02-27 09:21 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
```suggestion


```

2024-02-27 09:21 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
>  */!*
```suggestion
*/!*

```

2024-02-27 09:21 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
```suggestion


```

2024-02-27 09:21 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Один з основних прикладів - це ситуація, коли ми маємо велику кількість об'єктів бінарних зображень (наприклад, представлених у вигляді `ArrayBuffer` або `Blob`), і ми хочемо пов'язати ім'я або шлях
```suggestion
Один з основних прикладів - це ситуація, коли ми маємо велику кількість об'єктів бінарних зображень (наприклад, представлених у вигляді `ArrayBuffer` або `Blob`), і ми хочемо пов'язати ім'я або шлях з кожним зображенням.
Існуючі структури даних не зовсім підходять для таких цілей:
```

2024-02-27 09:21 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Один зі способів впоратися з цією проблемою - це періодично перевіряти кеш і видаляти "мертві" записи.
```suggestion
Один зі способів подолати цей недолік - це періодично перевіряти кеш і видаляти "мертві" записи.
```

2024-02-27 09:21 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
```suggestion


```

2024-02-27 09:21 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Але, як тільки цей елемент видалиться з DOM, логер повинен припинити надсилати повідомлення. Щоб відтворити видалення даного елемента, достатньо лише натиснути на кнопку "Закрити" у правому верхньому
```suggestion
Але, як тільки цей елемент видалиться з DOM, логер повинен припинити надсилати повідомлення.
Щоб відтворити видалення даного елемента, достатньо лише натиснути на кнопку "Закрити" у правому верхньому куті.  
```

2024-02-27 09:21 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Для того, щоб нам не ускладнювати роботу, і не сповіщати сторонній код кожен раз, коли наш DOM-елемент доступний, а коли – ні, достатньо буде створити на нього слабке посилання за допомогою `WeakRef`
```suggestion
Для того, щоб нам не ускладнювати роботу, і не сповіщати сторонній код кожен раз, коли наш DOM-елемент доступний, а коли - ні, достатньо буде створити для нього слабке посилання за допомогою `WeakRef`.  
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +    Даний функціонал підтримується у більшості сучасних браузерів. Після виконаних дій <code>alert</code> спрацює невідкладно.
```suggestion
   <br>
    Даний функціонал підтримується у більшості сучасних браузерів. Після виконаних дій <code>alert</code> спрацює невідкладно.
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Тепер давайте розглянемо вихідний код детальніше (вкладка `index.js`):
```suggestion
Тепер давайте розглянемо вихідний код детальніше (*вкладка `index.js`*):  
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +    ![](google-chrome-developer-tools.png)
```suggestion
   ![](google-chrome-developer-tools.png)
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +   У Google Chrome, наприклад, для цього потрібно відкрити інструменти розробника (`key:Ctrl` + `key:Shift` + `key:J` на Windows/Linux або `key:Option` + `key:⌘` + `key:J` на macOS), перейти до вклад
```suggestion
   У Google Chrome, наприклад, для цього потрібно відкрити інструменти розробника (`key:Ctrl` + `key:Shift` + `key:J` на Windows/Linux або `key:Option` + `key:⌘` + `key:J` на macOS), перейти до вкладки "Performance" та натиснути на кнопку з іконкою урни – "Collect garbage":  
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Його мета – надати можливість виконання додаткових операцій, пов'язаних з об'єктом, після його остаточного видалення з пам'яті.
```suggestion
Його мета - надати можливість виконання додаткових операцій, пов'язаних з об'єктом, після його остаточного видалення з пам'яті.  
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +**Реєстр** (або `FinalizationRegistry`) - це спеціальний об'єкт у JavaScript, який керує реєстрацією та скасуванням реєстрації об'єктів та їх колбеків очищення.
```suggestion
**Registry** (або `FinalizationRegistry`) - це спеціальний об'єкт у JavaScript, який керує реєстрацією та скасуванням реєстрації об'єктів та їх колбеків очищення.  
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Для створення екземпляра реєстру `FinalizationRegistry`, необхідно викликати його конструктор,
```suggestion
Для створення екземпляра реєстру `FinalizationRegistry`, необхідно викликати його конструктор, який приймає єдиний аргумент - колбек очищення (фіналізатор).
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +який приймає єдиний аргумент - колбек очищення (фіналізатор).
```suggestion
```

2024-02-28 10:19 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +  `target` - об'єкт, що реєструється для відстеження. Якщо `target` буде видалено збирачем сміття, колбек очищення буде викликано з `heldValue` як аргумент.
```suggestion
  `target` - об'єкт, що реєструється для відстеження. Якщо `target` буде видалено збирачем сміття, колбек очищення буде викликано з аргументом `heldValue`.
```

2024-03-01 11:44 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Це означає, що на момент створення колажу збирач сміття ще не видалив наше зображення, і ми сміливо взяли його з кеша,
```suggestion
Це означає, що на момент створення колажу збирач сміття ще не видалив наше зображення, і ми сміливо взяли його з кеша,
</br><br>
```

2024-03-01 11:44 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Давайте ще трохи "пограємо", замінивши одне із зображень ще раз і створивши новий колаж:
```suggestion
<br>
Давайте ще трохи "пограємо", замінивши одне із зображень ще раз і створивши новий колаж:  
</br><br>
```

2024-03-01 11:45 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +![](weakref-finalizationregistry-demo-07.gif)
```suggestion
![](weakref-finalizationregistry-demo-07.gif)
```

2024-03-01 11:45 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Цього разу результат ще більш значний. З 4 обраних зображень, 3 з них були взяті зі слабкого кешу, і тільки одне довелося завантажити з мережі.
```suggestion
<br>
Цього разу результат ще більш значний. З 4-ьох обраних зображень, 3-ри з них були взяті зі слабкого кешу, і тільки одне довелося завантажити з мережі.
```

2024-03-01 11:46 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Зниження навантаження на мережу склало близько 75%. Вражає, чи не так?
```suggestion
Зниження навантаження на мережу склало близько 75%. Вражає, чи не так?
</br><br>
```

2024-03-01 11:46 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Звісно, не слід забувати, що така поведінка не є гарантованою, і залежить від конкретної реалізації та роботи збирача сміття.
```suggestion
</br>
Звісно, не слід забувати, що така поведінка не є гарантованою, і залежить від конкретної реалізації та роботи збирача сміття.  
```

2024-03-01 11:47 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Виходячи з цього, одразу ж виникає цілком логічне запитання: чому б нам не використати звичайний кеш, де ми можемо самі керувати його сутностями, а не покладатися на збирач сміття?
```suggestion
Виходячи з цього, одразу ж виникає цілком логічне запитання: чому б нам не використати звичайний кеш, де ми можемо самі керувати його вмістом, а не покладатися на збирач сміття?
```

2024-03-01 11:57 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +## Отже:
```suggestion
## Підсумки
```

2024-03-01 11:57 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Це корисно для розв'язання проблеми надмірного використання пам'яті та оптимізації використання системних ресурсів у додатках.
```suggestion
Це корисно для розв'язання проблеми надмірного використання пам'яті та оптимізації використання системних ресурсів у застосунках.  
```

2024-03-01 11:58 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +`FinalizationRegistry` - це засіб реєстрації колбеків, які виконуються під час знищення об'єктів, на які більше немає сильних посилань. Це дає змогу звільняти пов'язані з об'єктом ресурси або виконув
```suggestion
`FinalizationRegistry` - це засіб реєстрації колбеків, які виконуються під час знищення об'єктів, на які більше немає сильних посилань.
Це дає змогу звільняти пов'язані з об'єктом ресурси або виконувати інші необхідні операції перед видаленням об'єкта з пам'яті.
```

2024-03-01 11:59 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/weakref-finalizationregistry.view/index.html
> +<html lang="uk">
```suggestion
<html lang="en">
```

2024-03-01 12:04 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +тим самим скоротивши кількість мережевих запитів і прискоривши загальний час процесу створення колажу:
```suggestion
```

2024-03-01 12:04 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
>  </br><br>
```suggestion
тим самим скоротивши кількість мережевих запитів і прискоривши загальний час процесу створення колажу:
</br><br>
```

2024-03-01 12:04 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +Звісно, не слід забувати, що така поведінка не є гарантованою, і залежить від конкретної реалізації та роботи збирача сміття.
```suggestion

Звісно, не слід забувати, що така поведінка не є гарантованою, і залежить від конкретної реалізації та роботи збирача сміття.  
```

2024-03-01 12:04 UTC, dolgachio commented on 1-js/99-js-misc/07-weakref-finalizationregistry/article.md
> +`WeakRef` - призначений для створення слабких посилань на об'єкти, що дозволяє їм бути видаленими з пам'яті збирачем сміття, якщо на них більше немає сильних посилань.
```suggestion

`WeakRef` - призначений для створення слабких посилань на об'єкти, що дозволяє їм бути видаленими з пам'яті збирачем сміття, якщо на них більше немає сильних посилань.
```

2024-03-01 12:06 UTC, dolgachio approved these changes

2024-03-01 12:07 UTC, merged