Update article.md
javascript-tutorial/uk.javascript.info pull request #629
Opened 2024-05-09 09:01 UTC by taleksina

Розділ 3.5. Помилка у слові "всередині", написано "всереді". #551

2024-05-14 21:01 UTC, alexandrtovmach approved these changes
LGTM!

2024-08-29 01:23 UTC, tarasyyyk requested changes

2024-08-29 01:23 UTC, tarasyyyk commented on 1-js/03-code-quality/05-testing-mocha/article.md
> +: Код, всередині блоку `it`, якщо реалізація правильна, повинен виконуватись без помилок.
```suggestion
: Код всередині блоку `it` має виконуватись без помилок, якщо реалізація правильна.
```

2024-08-29 01:27 UTC, merged

2024-08-29 01:28 UTC, tarasyyyk commented
@taleksina, дякуємо за внесок!