[fix] errors for #659
javascript-tutorial/uk.javascript.info pull request #661
Opened 2024-10-02 19:32 UTC by lylich0

Closes #659 

Accidentally closed the previous pull request without merging and deleted the forked repository.

2024-10-04 16:08 UTC, RiinaVi commented on 5-network/01-fetch/article.md
> +У прикладі нижче, є елемент `<canvas>`, на котрому можна малювати рух мишки. При натисканні на кнопку "відправити", то зображен буде відправлено на сервер:
"зображен" -> "зображення"

2024-11-02 20:33 UTC, dolgachio requested changes
Дякую за виправлення! 
Я там дещо виправив, але я сам внесу ці зміни

2024-11-02 20:33 UTC, dolgachio commented on 5-network/01-fetch/article.md
> +На цьому етапі можна перевірити статус HTTP-запиту, та визначити, чи виконався він успішно, а також переглянути заголовки, але поки що без тіла запиту.
👍

2024-11-02 20:33 UTC, dolgachio commented on 5-network/01-fetch/article.md
> +У прикладі нижче, є елемент `<canvas>`, на котрому можна малювати рух мишки. При натисканні на кнопку "відправити", то зображен буде відправлено на сервер:
```suggestion
У прикладі нижче, є елемент `<canvas>`, на котрому можна малювати рух мишки. При натисканні на кнопку "відправити", то зображення буде відправлено на сервер:
```

2024-11-02 20:33 UTC, dolgachio commented on 5-network/01-fetch/article.md
> +Типовий запит за допомогою `fetch` складається із двох операторів `await`:
```suggestion
Типовий запит за допомогою `fetch` складається з двох операторів `await`:
```

2024-11-02 20:33 UTC, dolgachio commented on 5-network/01-fetch/article.md
> +let commits = await response.json(); // прочитати тіло відповіді і розпарсити як JSON
```suggestion
let commits = await response.json(); // прочитати тіло відповіді як JSON
```

2024-11-02 20:34 UTC, dolgachio commented
@all-contributors add @lylich0 for bug

2024-11-02 20:34 UTC, dolgachio approved these changes
👍

2024-11-02 20:35 UTC, merged